var keymirror = require('keymirror');

module.exports = keymirror({
  BATCH_EDIT_COLUMN_DEFINE_PARENT: null,
  BATCH_EDIT_COLUMN_MODIFY_DATATYPE: null,
  BATCH_EDIT_COLUMN_RENAME: null,
  BATCH_EDIT_COLUMN_UNIQUENESS: null,
  BATCH_EDIT_COLUMN_VISIBILITY: null,
  BATCH_EDIT_MODE_TOGGLE: null,
  BATCH_EDIT_SELECT_ALL_TABLES: null,
  BATCH_EDIT_SELECT_ALL_COLUMNS: null,
  BATCH_EDIT_SET_COLUMN_STATE: null,
  BATCH_EDIT_SET_TABLE_STATE: null,
  BATCH_EDIT_TABLE_VISIBILITY: null
});
