import keymirror from 'keymirror';

module.exports = keymirror({
  COOKIE_EXPIRE_SESSION_FILTERS: null,
  COOKIE_RESET_ALL_SESSION_DYNAMIC_FILTERS: null,
  COOKIE_SET_SESSION_FILTERS: null,
  COOKIE_UPDATE_SESSION_FILTER_FILTER_STATE: null,
  COOKIE_UPDATE_YELLOWFIN_STUDY_CACHE_FILTERS: null,
});
