import keymirror from 'keymirror';

export const reviewedByTypes = keymirror({
  ALL_RECORDS: null,
  UNREVIEWED_BY_ME: null,
  UNREVIEWED_BY: null
});

export default keymirror({
  DATA_REVIEW_CREATE_ROLE: null,
  DATA_REVIEW_DELETE_ROLES: null,
  DATA_REVIEW_FETCH_TABULAR_REPORT_NAMES: null,
  DATA_REVIEW_FETCH_USER_ENTITY_ROLES: null,
  DATA_REVIEW_GET_REVIEW_SETS: null,
  DATA_REVIEW_IMPORT_FILE: null,
  DATA_REVIEW_LOAD_ROLE: null,
  DATA_REVIEW_LOAD_ROLES: null,
  DATA_REVIEW_LOAD_ROLES_WITH_PAGE_SETTINGS: null,
  DATA_REVIEW_UPDATE_USER_ROLES: null,
  DATA_REVIEW_UPDATE_ROLE: null,
  DATA_REVIEW_UPDATE_ROLES_FOR_USER_ENTITIES: null,
  ADMIN_GET_REVIEW_ROLES_USAGE_DATA: null,
  DATA_REVIEW_VALIDATE_FILE: null,
  GET_REVIEW_ROLES_USAGE_DATA_FOR_REPORTS: null
});
