module.exports = {
  ADD_MENU_ADD_TYPES: {
    CREATE_FOLDER: 'CREATE_FOLDER',
    DASHBOARD: 'DASHBOARD',
    GRAPHICAL_REPORT: 'GRAPHICAL_REPORT',
    DATA_REVIEW_SET: 'DATA_REVIEW_SET',
    MONITOR: 'MONITOR',
    QUALITY_AGREEMENT: 'QUALITY_AGREEMENT',
    TABULAR_REPORT: 'TABULAR_REPORT'
  },
  ADHOC_REPORT_TABS: {
    TEMPLATE: 'TEMPLATE',
    DATA: 'DATA',
    OPTIONS: 'OPTIONS'
  },
  APPLIED_FILTER_TYPE_DROPDOWN: 'DROPDOWN',
  APPLIED_FILTER_TYPE_SLIDER: 'SLIDER',
  APPLIED_FILTER_TYPE_DATE: 'DATE',
  APPLIED_FILTER_TYPE_DROPDOWN_SINGLE_SELECT : 'DROPDOWN_SINGLE_SELECT',
  APPLIED_FILTER_TYPE_RANGE: 'RANGE',
  AUDIT_ACTION_CREATE: 'CREATE',
  AUDIT_ACTION_DELETE: 'DELETE',
  AUDIT_ACTION_UPDATE: 'UPDATE',
  BUILTIN_TYPE_TASKS: 'TASKS',
  BUILTIN_TYPE_MONITORS: 'MONITORS',
  BUILTIN_TYPE_DATA_MONITOR_KPI_1: 'DATA_MONITOR_KPI_1',
  BUILTIN_TYPE_SITE_SCORECARD: 'SITE_SCORECARD',
  BUILTIN_TYPE_DATA_DIFF: 'DATA_DIFF',
  BUILTIN_TYPE_SCORECARD: 'SCORECARD',
  BUILTIN_TYPE_DATA_REVIEW_SUMMARY: 'DATA_REVIEW_SUMMARY',
  COLUMN_TYPES: {
    FILTERED_COLUMN: 'FILTERED_COLUMN',
    FUNCTION_COLUMN: 'FUNCTION_COLUMN',
    PROPERTY_COLUMN: 'PROPERTY_COLUMN',
    SELECTION_CONDITION_COLUMN: 'SELECTION_CONDITION_COLUMN',
    VALUE_COLUMN: 'VALUE_COLUMN'
  },
  COMBOBOX_ABBREVIATION_VALUE: 'abbreviation-value',
  CONTENT_PLACEHOLDER_HEIGHT_REM_DEFAULT: 48,
  CONTENT_PLACEHOLDER_HEIGHT_REM_HALF: 24,
  CREATE_FOLDER_DUPLICATE: 'CREATE_FOLDER_DUPLICATE',
  CREATE_FOLDER_EMPTY: 'CREATE_FOLDER_EMPTY',
  CREATE_FOLDER_VALID: 'CREATE_FOLDER_VALID',
  DATA_REVIEW_UPDATE_TYPES: {
    NEW: 'NEW',
    UPDATED: 'UPDATED',
    DELETED: 'DELETED',
    NONE: 'NONE'
  },
  DATA_SELECTOR_FILTERS: 'DATA_SELECTOR_FILTERS',
  DATA_SELECTOR_PARAMETERS: 'DATA_SELECTOR_PARAMETERS',
  DATA_QUALITY_DASHBOARD: 'Data Quality Dashboard',
  DOWN: 'DOWN',
  DOWNLOAD_TYPE_CSV: 'CSV',
  DOWNLOAD_TYPE_XLSX: 'XLSX',
  DOWNLOAD_TYPE_PDF: 'PDF',
  EMBEDDED_REPORTS_ENTRY_TYPES: {
    DASHBOARDS_ENTRY: 'DASHBOARD',
    VIEW_DASHBOARDS_ENTRY: 'VIEWDASHBOARD',
    KPI_STUDIO_ENTRY: 'REPORTLIST',
    REPORT_ENTRY: 'VIEWREPORT',
    CUSTOM_ANALYTICS_ENTRY: 'BROWSE',
    REPORT_LIST_ENTRY: 'REPORTLIST'
  },
  FAVORITE_TYPE_FILE_WRAPPER: 'FILE_WRAPPER',
  FAVORITE_TYPE_TASK_WRAPPER: 'TASK_WRAPPER',
  FILE_TITLE_MAX_LENGTH: 100,
  FILE_TYPE_ANALYTICS: 'ANALYTICS',
  FILE_TYPE_BUILTIN: 'BUILTIN',
  FILE_TYPE_DASHBOARD: 'DASHBOARD',
  FILE_TYPE_DATA_REVIEW: 'DATA_REVIEW_SET',
  FILE_TYPE_FOLDER: 'FOLDER',
  FILE_TYPE_MONITOR: 'MONITOR',
  FILE_TYPE_OVERSIGHT_SCORECARD: 'oversight_scorecard_report',
  FILE_TYPE_QUALITY_AGREEMENT: 'QUALITY_AGREEMENT',
  FILE_TYPE_REPORT: 'REPORT',
  FILE_TYPE_TASK: 'TASK',
  FILE_TYPE_RACT: 'RACT',
  FILE_TYPE_EMBEDDED_REPORT: 'YELLOWFIN',
  FILE_TYPE_EMBEDDED_DASHBOARD: 'EMBEDDED_DASHBOARD',
  FILTER_CQL_MAX_LENGTH: 500,
  FILTER_TYPE_DYNAMIC: 'DYNAMIC',
  FILTER_TYPE_STATIC: 'STATIC',
  NO_ASSOCIATED_FILE: 'No Associated Report or Dashboard',
  HOME_PAGE_TAB_TYPES: {
    MY_DASHBOARDS: 'mydashboards',
    FAVORITES: 'favorites'
  },
  HOME_PAGE_FILE_TYPES: {
    FILE: 'file',
    YF_REPORT: 'yf_report',
    YF_DASHBOARD: 'yf_dashboard',
    OVERSIGHT_SCORECARD: 'oversight_scorecard_report',
    BOT_DASHBOARD: 'bot',
    BOT_FAQ: 'botFaq'
  },
  MONITOR_TABS: {
    OVERVIEW: 'OVERVIEW',
    CONFIGURATION: 'CONFIGURATION'
  },
  MONITOR_THRESHOLD_TYPE: {
    LOWER_BAND: {
      text: 'Lower Band (breaches when score is below threshold)',
      value: 'LOWER_BAND'
    },
    UPPER_BAND: {
      text: 'Upper Band (breaches when score is above threshold)',
      value: 'UPPER_BAND'
    }
    // TODO: Enable when supports IN_BAND and OUT_BAND.
    //    IN_BAND: {
    //      text: 'In band',
    //      value: 'IN_BAND'
    //    },
    //    OUT_BAND: {
    //      text: 'Out band',
    //      value: 'OUT_BAND'
    //    }
  },
  MONITOR_THRESHOLD_TYPE_DESCRIPTION: {
    LOWER_BAND: 'A breach occurs if score is below threshold',
    UPPER_BAND: 'A breach occurs if score is above threshold'
  },
  MONITOR_STATE: {
    ACTIVE: {
      text: 'Active',
      value: 'ACTIVE_MONITOR'
    },
    RECORDING: {
      text: 'Recording',
      value: 'RECORDING_MONITOR'
    },
    INACTIVE: {
      text: 'Inactive',
      value: 'INACTIVE_MONITOR'
    }
  },
  //  This is due to a limitation for immutable.js to convert an immutable to JSON.
  //  TP 9053 for this issue.
  HIGHCHART_MULTISELECT_MAX_POINTS: 500,
  LIST_FILTER_TARGET_FOLDERS: 'folders',
  LIST_FILTER_TARGET_TASKS: 'tasks',
  LIST_FILTER_TYPE_DROPDOWN: 'DROPDOWN',
  LIST_FILTER_TYPE_TOGGLE: 'TOGGLE',
  MONITOR_DESCRIPTION_LETTER_COUNT_LIMIT: 180,
  MONITOR_OVERVIEW_TAB_SIZE: 350,
  MONITOR_PREVIEW_JOB_COMPLETED: 'MONITOR_PREVIEW_JOB_COMPLETED',
  MONITOR_PREVIEW_JOB_FAILURE: 'MONITOR_PREVIEW_JOB_FAILURE',
  MONITOR_PREVIEW_JOB_IN_PROGRESS: 'MONITOR_PREVIEW_JOB_IN_PROGRESS',
  MONITOR_STATE_ACTIVE: 'ACTIVE_MONITOR',
  MONITOR_STATE_RECORDING: 'RECORDING_MONITOR',
  MONITOR_STATE_INACTIVE: 'INACTIVE_MONITOR',
  MONITOR_NUMERIC_DECIMAL_PLACES_LIMIT: 5,
  NULL: 'NULL',
  NUMERIC_INPUT_BOX_DECREMENT: 'NUMERIC_INPUT_BOX_DECREMENT',
  NUMERIC_INPUT_BOX_INCREMENT: 'NUMERIC_INPUT_BOX_INCREMENT',
  OVERSIGHT_REPORT: '11111111-1111-1111-1111-111111111111',
  PORTFOLIO_SUMMARY: 'Portfolio Summary',
  QUALITY_AGREEMENT_CRO_ID: 'croId',
  QUALITY_AGREEMENT_CRO_NAME: 'croName',
  QUALITY_AGREEMENT_STUDY_ID: 'studyId',
  QUALITY_AGREEMENT_STUDY_NAME: 'studyName',
  QUALITY_AGREEMENT_THRESHOLD_TYPES: {
    TARGET: 'target',
    MAX: 'max'
  },
  RBAC_ENTITY_TYPE_GROUP_ENTITY: 'GROUP_ENTITY',
  RBAC_ENTITY_TYPE_USER_ENTITY: 'USER_ENTITY',
  RENAME_FOLDER_DUPLICATE: 'RENAME_FOLDER_DUPLICATE',
  RENAME_FOLDER_EMPTY: 'RENAME_FOLDER_EMPTY',
  RENAME_FOLDER_INVALID: 'RENAME_FOLDER_INVALID',
  RENAME_FOLDER_VALID: 'RENAME_FOLDER_VALID',
  REPORT_TYPE_GRAPHICAL: 'GRAPHICAL',
  REPORT_TYPE_TABULAR: 'TABULAR',
  REPORTS_LANDING_PAGE_ID: 'landing-page',
  // The `study` table long name is `Study` and the `studyname`
  // column long name is `Study Name` for CDM Schema.
  STUDY_SESSION_FILTER_COLUMN_LONG_NAME: 'Study Name',
  STUDY_SESSION_FILTER_CQL: 'study.studyname',
  STUDY_SESSION_FILTER_TABLE_LONG_NAME: 'Study',
  STUDY_SUMMARY: 'Study Summary',
  TASK_STATE_CANCELLED: 'CANCELLED',
  TASK_STATE_CLOSED: 'CLOSED',
  TASK_STATE_OPEN: 'OPEN',
  TEMPLATE_TYPE_CHART: 'CHART_TEMPLATE',
  TEMPLATE_TYPE_TABULAR: 'TABULAR_TEMPLATE',
  TREE_VIEW_SEARCH_TIMEOUT: 500,
  UP: 'UP',
  A4: 'A4',
  A3: 'A3',
  A2: 'A2',
  A1: 'A1'
};
