// WARNING: Do not require util.js here -- this will cause a circular dependency that will lead to
// functionality breaking.
import React from 'react';
import Moment from 'moment';
import DOM from 'react-dom-factories';
import ExposureAppConstants from '../constants/ExposureAppConstants';
import ExposureSharingConstants from '../constants/ExposureSharingConstants';

const span = DOM.span;

/**
 * The constants inside of this file are intended to be display strings which are shown to end users. Having them
 * isolated here could help with possible future internationalization / translation work, as well as having a set of
 * common constants which could be reused throughout the application. Functional constants should be included in
 * separate constants files.
 */

const constants = {
  ACCOUNT_ADMIN_CREATION_FAILURE: function (accountName, accountAdminEmail) {
    return `Admin ${accountAdminEmail} could not be added to ${accountName}.`;
  },
  ACCOUNT_ADMIN_CREATION_SUCCESS: function (accountName, accountAdminEmail) {
    return `Admin ${accountAdminEmail} successfully added to ${accountName}.`;
  },
  ACCOUNT_ADMIN_EMAIL: "Account Admin's Email Address",
  ACCOUNT_CONFIRMATION_SUCCESS: function (accountName, isConfirmed, hasMoreThan1Account) {
    return span(null,
      `${hasMoreThan1Account ? '' : 'Thank you for signing up with Saama LSAC. '}You have${isConfirmed ? ' already' : ''} been added to the `,
      span({ className: 'semi-bold' }, `'${accountName}' `),
      `account.`,
    );
  },
  ACCOUNT_CREATION_FAILURE: function (accountName, accountAdminEmail) {
    return `Account ${accountName} with admin ${accountAdminEmail} could not be added.`;
  },
  ACCOUNT_CREATION_SUCCESS: function (accountName, accountAdminEmail) {
    return `Account ${accountName} with admin ${accountAdminEmail} successfully added.`;
  },
  ACCOUNT_DISPLAY_NAME: 'Account Display Name',
  ACCOUNT_MANAGEMENT: 'Account Management',
  ACCOUNT_NAME: 'Account Name',
  ACCOUNT_ROLE_BASIC: 'Basic',
  ACCOUNT_ROLE_ADVANCED: 'Advanced',
  ACCOUNT_ROLE_ADMIN: 'Admin',
  ACCOUNT_STATUS: 'Account Status',
  ACCOUNTS_FAILED_TO_LOAD: 'Status update: Accounts could not be loaded at this time.',
  ACTION_TAKEN: 'Action taken',
  ACTIONS: 'Actions',
  ACTIVE: 'Active',
  ADD: 'Add',
  ADD_A_COMMENT: 'Add a comment',
  ADD_A_DATA_ACCESS_GROUP: 'Add a data access group',
  ADD_A_TASK: 'Add Task',
  ADD_A_TEAM: 'Add a team',
  ADD_A_STUDY: 'Add a study',
  ADD_A_USER: 'Add a user',
  ADD_ACCOUNT_ADMIN: 'Add Account Admin',
  ADD_CHILDREN: 'Add children',
  ADD_CONDITIONAL_FILTER: 'Add Conditional Filter',
  ADD_DATA_REVIEW_ROLE: 'Add Data Review Role',
  ADD_DYNAMIC_FILTER: 'Add Dynamic Filter',
  ADD_FILTER: 'Add filter',
  ADD_METRIC_GROUP: 'Add Metric Group',
  ADD_MORE_ASSIGNEES: 'Add more assignees',
  ADD_MORE_USERS: 'Add more user(s)',
  ADD_MULTIPLE_USERS: 'Add multiple users',
  ADD_NEW_SESSION_FILTER: 'Add new session filter',
  ADD_PAGES_TO_YOUR_HOME: 'You can add pages to your Home by clicking',
  ADD_STUDIES_TO_THIS_DATA_ACCESS_GROUP: 'Add studies to this data access group',
  ADD_TO_HOME_PAGE: 'Add to home page',
  ADD_THIS_DATA_ACCESS_GROUP: 'Add this data access group',
  ADD_THIS_DATA_REVIEW_ROLE: 'Add this data review role',
  ADD_THIS_TASK: 'Submit',
  ADD_THIS_TEAM: 'Add this team',
  SUBMIT_HOME_PAGE_SUCCESSFUL: 'Home page submitted successfully',
  SUBMIT_HOME_PAGE_UNSUCCESSFUL: 'Home page submission was unsuccessful',
  DELETE_HOME_PAGE_SUCCESSFUL: 'Home page deleted successfully',
  DELETE_HOME_PAGE_UNSUCCESSFUL: 'Home page deletion was unsuccessful',
  ADD_USERS: 'Add users',
  ADD_USERS_AND_OR_TEAMS: 'Add users and/or teams',
  ADD_USERS_TO_THIS_TEAM: 'Add users to this team',
  ADDITIONAL_DYNAMIC_FILTER: 'Additional dynamic filter',
  ADDITIONAL_STATIC_FILTER: 'Additional static filter',
  ADDING_A_USER_IS_REQUIRED: 'Adding a user is required.',
  ADHOC_REPORT_TAB_DISPLAY_NAME: {
    [ExposureAppConstants.ADHOC_REPORT_TABS.TEMPLATE]: '1. Template',
    [ExposureAppConstants.ADHOC_REPORT_TABS.DATA]: '2. Data',
    [ExposureAppConstants.ADHOC_REPORT_TABS.OPTIONS]: '3. Options',
  },
  ADJUST_THE_SENSITIVITY_OF_THE_THRESHOLD: 'adjusts the sensitivity of the threshold.',
  ADMIN: 'Admin',
  ADVANCED: 'Advanced',
  ADVANCED_CONFIGURATION: 'Advanced configuration',
  ADVANCED_REPORT: 'Advanced Analytics',
  ACCEPT_POLICY_AND_AGREEMENTS_ERROR: 'Accept Policy and Agreements error',
  AFFECTED_DASHBOARDS: 'Affected dashboards:',
  AGGREGATE: 'Aggregate',
  ALL: 'All',
  ALL_FIELDS_REQUIRED: 'All fields required.',
  ALL_SELECTED: 'All selected',
  INCLUDE_ARCHIVED: 'Include Archived',
  ALL_ACTIVE: 'All Active',
  ALL_ARCHIVED: 'All Archived',
  ALL_SELECTED_DATA_ACCESS_GROUPS_MUST_BE_EMPTY_TO_DELETE: 'All selected data access groups must be empty to delete.',
  ALL_SELECTED_DATA_REVIEW_ROLES_MUST_BE_UNUSED_TO_DELETE: 'All selected data review roles must be unused to delete.',
  ALL_STUDIES: 'All Studies',
  ALL_SUBJECTS: 'All Subjects',
  ALL_VALUES_SELECTED: 'All values selected',
  ALLOW_REPORT_VIEWER_TO_CONFIGURE: 'Allow analytics viewer to configure',
  AMOUNT_OF_IS_ABOVE: function (name, count, limit) {
    return `You have exceeded the maximum number of`
      + ` ${name} allowed: ${count} (${limit} maximum allowed)`;
  },
  ANALYTICS: 'Analytics',
  AN_AGREEMENT: 'I agree',
  AN_AGREEMENT_CHECKBOX: 'I acknowledge that I have read and agree to the above Policy Updates',
  TASK_ACCESS: 'Task Access',
  TASK_TITLE: 'Task Title',
  GO_TO_COLLABORATION:'Go to Collaboration',
  RACT_ACCESS: 'Ract Access',
  API_ACCESS: 'API Access',
  APPLICABLE_ENTITIES: 'Applicable Entities',
  APPLY: 'Apply',
  METRIC_WEIGHTS_TOOLTIP_MESSAGE: 'are used to calculate the score for each data point. When a score exceeds the threshold, a monitor event is triggered.',
  ARE_YOU_SURE: 'Are you sure?',
  ASCENDING_ORDER: function (label) {
    return `${label} (Ascending)`;
  },
  ASSIGNEE: 'Assignee',
  ASSIGNED_TO_ME:'Assigned to me',
  ASSOCIATED_REPORTS_AND_DASHBOARDS: 'Associated Analytics and Dashboards',
  AT_LEAST_3_CHARACTER_TYPES: 'Must contain 3 of the following types: uppercase letters, lowercase letters, numbers, and special characters.',
  AT_LEAST_10_CHARACTERS: 'Must be 10 or more characters.',
  AT_MOST_72_CHARACTERS: 'Must be 72 or less characters.',
  AVAILABLE_METRICS: 'AVAILABLE METRICS',
  AVAILABLE_REVIEW_ROLES: 'Available Review Roles',
  ATTACH:'Attach',
  ASSIGN_TO:'Assign to ',
  ASC:'asc',
  BACK: 'Back',
  BACK_TO_DASHBOARD: 'Back to Dashboard',
  BACK_TO_REPORT: 'Back to Analytics',
  BACK_TO_REPORT_LIST: 'Back to Analytics List',
  BASIC: 'Basic',
  BATCH_USERS_ERROR_ALREADY_EXISTS: 'Already exist in the current account. No invitations have been sent to these users.',
  BATCH_USERS_ERROR_ACCOUNT_WITH_IDP_ALREADY_EXISTS: 'Already belong in other accounts that have IdPs set. No invitations have been sent to these users.',
  BATCH_USERS_ERROR_INVALID: 'Are invalid email format. Users with invalid email formats cannot be added.',
  BATCH_USERS_ERROR_ROLE_INVALID: 'Invalid role. Users with invalid role cannot be added.',
  BATCH_USERS_STEP_1: 'Step 1: Download CSV & fill in emails and roles',
  BATCH_USERS_STEP_2: 'Step 2: Upload CSV',
  BATCH_USERS_SUCCESS: function (numUsers) {
    return `${numUsers} ${numUsers > 1 ? 'invitations have' : ' invitation has'} been sent. Status will remain as 'pending' until the user registers in LSAC.`;
  },
  BREACH: 'Breach',
  BREACHES: 'Breaches',
  BROWSE: 'Browse',
  BROWSE_TEMPLATES: 'Browse templates',
  BUILTIN: 'Built-in Report',
  BULLET: '•',
  CAN_EDIT: 'Edit',
  CAN_EDIT_DEFAULT_OVERSIGHT_SCORECARD_PROFILE: 'Can Edit Default Oversight Scorecard Profile',
  CAN_AGGREGATE: 'can aggregate',
  CAN_AGGREGATE_HELP_TEXT: 'The following aggregate functions can be applied in this parameter:  Count - count(), Maximum - max(), Mean - avg(), Median - median(), Minimum - min(), Standard Deviation - stddev(), Sum - sum()',
  CANCEL: 'Cancel',
  CANCEL_KEEP_SETTINGS: 'Cancel, keep settings',
  CANCELLED: 'Cancelled',
  CANNOT_CONTAIN_OTHER_FIELDS: 'Cannot contain first name, last name, or email.',
  CATEGORY: 'Category',
  FIRST_NAME_EMPTY_IN_PASSWORD: 'First name is required. Please enter first name.',
  LAST_NAME_EMPTY_IN_PASSWORD: 'Last name is required. Please enter last name.',
  CANNOT_DELETE_YOUR_OWN_ACCOUNT: 'You cannot delete your own account.',
  CANNOT_EXECUTE_QUERY: 'Cannot execute query due to invalid CQL.',
  CANNOT_FIND_USER: 'Cannot find user',
  CHANGE: 'Change',
  CHANGE_USER_DATA_ACCESS_GROUP_FAILED: 'Changing user access group failed.',
  CHANGE_USER_DATA_REVIEW_ROLES_FAILED: 'Changing user data review roles failed.',
  CHANGE_USER_DETAILS_FAILED: 'Changing user details failed.',
  CHANGE_USER_ROLE_FAILED: 'Changing user role failed.',
  CHANGING_TEMPLATE_WARNING: 'Changing your template selection will cause you to lose any content you have entered on Step 2',
  CHART: 'Chart',
  CHECKMARK: '\u2713',  // An HTML entity can't be used in dynamic content: https://facebook.github.io/react/docs/jsx-gotchas.html
  CLEAR: 'Clear',
  CLEAR_ALL: 'Clear All',
  CLINICAL_ATTRIBUTES: 'Clinical Attributes',
  CLOSE: 'Close',
  CLOSED: 'Closed',
  COMMENTS_AND_HISTORY: 'Comments & History',
  COMPREHEND_SCHEMA: 'Comprehend Schema',
  CONDITIONAL_FILTER: 'Conditional filter',
  CONFIGURATION: 'Configuration',
  CONFIGURATION_HAS_NOT_BEEN_SAVED: 'Configuration has not been saved',
  CONFIGURATION_OPTIONS_FOR: function (templateName) {
    return `Configuration options for "${templateName}"`;
  },
  CONFIGURE: 'Configure',
  CONFIGURE_OVERSIGHT_SCORECARD: 'Configure Oversight Scorecard',
  CONFIGURE_METRICS: 'Configure metrics',
  CONFIGURE_TEAM_HOME_PAGES: 'Configure Team Home Pages',
  CONFIRM: 'Confirm',
  CONFIRM_PASSWORD: 'Confirm Password',
  CONTACT_ADMIN: 'Please contact your account administrator if you need additional help.',
  CONTINUE: 'Continue',
  CUSTOMIZE_TASK: 'Customize',
  CORE_ATTRIBUTES: 'Core Attributes',
  COMPREHEND_UPDATE_TIME: 'Comprehend Update Time',
  COULD_NOT_DELETE_DATA_ACCESS_GROUPS: 'Could not delete data access group(s)',
  COULD_NOT_DELETE_DATA_REVIEW_ROLES: 'Could not delete data review role(s)',
  COULD_NOT_DELETE_USERS: 'Could not delete user(s).',
  COUNT: 'Count',
  COUNT_OF_SUBJECT: 'Count of subject',
  COUNT_OF_SUBJECT_BY_RACE_SEX: 'Count of Subject by Race, Sex',
  COUNTRIES: 'Countries',
  COUNTRY: 'Country',
  CQL: 'CQL',
  CREATE: 'Create',
  CREATED_BY_ME:'Created by me',
  CREATE_ACCOUNT: 'Create Account',
  CREATE_ANALYTICS_DASHBOARDS_FOLDERS: 'Create analytics, dashboards and folders',
  CREATE_DASHBOARD: 'Create Dashboard',
  CREATE_DATA_REVIEW: 'Create Data Review Set',
  CREATE_EDIT_DELETE_SCHEMAS: 'Create / Edit / Delete Comprehend schemas',
  CREATE_EDIT_DELETE_USERS: 'Create / Edit / Delete users in the account',
  CREATE_EDIT_MONITOR_DEFINITION: 'Create / Edit monitor definition',
  CREATE_FILE_UNSUCCESSFUL: function (fileType) {
    return `Status update: Create ${convertReportToAnalytics(fileType)} was unsuccessful.`;
  },
  CREATE_MONITOR: 'Create Monitor',
  CREATE_TABULAR_REPORT: 'Create Tabular Analytics',
  CREATE_TEMPLATE: 'Create Template',
  CREATE_TEMPLATE_ADVANCED_REPORT: 'Create Advanced Analytics',
  CREATE_TEMPLATE_SUCCESSFUL: 'Status update: Create template succeeded.',
  CREATE_TEMPLATE_UNSUCCESSFUL: 'Status update: Create template was unsuccessful.',
  CRO_NAME: 'CRO Name',
  CSV_EXPORT_FAILED: function (analyticTitle) {
    return `CSV export failed for analytics ${analyticTitle}.`;
  },
  CRA: 'CRA',
  CRO: "CRO",
  CURRENT_ACCOUNT: 'Current account',
  CURRENT_PREVIEW_REGIONS: 'Current regions (non simulated)',
  CURRENT_THRESHOLD: 'Current threshold',
  CUSTOM_ANALYTICS: 'Custom Analytics',
  CHANGE_STATUS: 'Change Status',
  CAPTURE_SCREENSHOT_AUTO:'AUTO',
  CAPTURE_SCREENSHOT_MANUAL:'MANUAL',
  CAPTURE_SCREENSHOT_NONE:'NONE',
  DASHBOARD: 'Dashboard',
  DASHBOARD_INFORMATION: 'Dashboard Information',
  DASHBOARD_PREVIEW: 'Dashboard Preview',
  DATA_ACCESS_GROUP: 'Data Access Group',
  DATA_ACCESS_GROUP_NAME_IS_ALREADY_IN_USE: 'Data Access Group name is already in use.',
  DATA_ACCESS_GROUP_NAME_IS_REQUIRED: 'Data Access Group name is required.',
  DATA_ACCESS_GROUP_STUDIES_IS_REQUIRED: 'You need to select at least one study.',
  DATA_ACCESS_GROUPS: 'Data Access Groups',
  DATA_ACCESS_GROUPS_MANAGEMENT: 'Data Access Groups Management',
  DATA_ACCESS_NAME: 'Data Access Name',
  DATA_CHANGE_SUMMARY: 'Data Change Summary',
  DATA_ELEMENTS_FOR: function (templateName) {
    return `Data elements for "${templateName}"`;
  },
  DATA_FRAME: 'Data Frame',
  DATA_MONITOR_RESULTS: 'Data Monitor Results',
  DATA_MONITOR_RUN_ERROR: 'Data monitor run error',
  DATE_OUT_OF_BOUNDS: function (lowerBound, upperBound) {
    return `The date must be between ${lowerBound} and ${upperBound}.`;
  },
  DATA_REVIEW_EXPORT_FILE: 'Download Review File',
  DATA_REVIEW_DETAILS: 'Data review details',
  DATA_REVIEW_DETAILS_DATA_ERROR: 'Failed to get detailed data for data review set',
  DATA_REVIEW_DETAILS_HEADER: (reportTitle, startDate, endDate) => {
    return `${reportTitle} Start: ${startDate} End: ${endDate}`;
  },
  DATA_REVIEW_DETAILS_ROWS_LIMITED: 'Results for Data Review Sets are limited to 30 rows per listing. You can view the full results by exporting to Excel.',
  DATA_REVIEW_FROM_DATE: 'Last Review',
  DATA_REVIEW_IMPORT_FILE: 'Import Review File',
  DATA_REVIEW_INFORMATION: 'Data Review Set Information',
  DATA_REVIEW_PAST_IMPORTS_EXPORTS: 'Previous Exports/Imports',
  DATA_REVIEW_PREVIEW: 'Data Review Set Preview',
  DATA_REVIEW_PLEASE_SELECT_FILTERS: 'Please select a study, a date range and an included records by using the Study, Data Update Range and Included Records filters to the left.',
  DATA_REVIEW_ROLE_NAME: 'Data Review Role Name',
  DATA_REVIEW_ROLES: 'Data Review Roles',
  DATA_REVIEW_ROLES_MANAGEMENT: 'Data Review Roles Management',
  DATA_REVIEW_ROLES_USAGE_DATA_ERROR: 'Failed to get data review roles usage data',
  DATA_REVIEW_ROLE_NAME_EXISTS: 'Error: There is already a Data Review Role with the same name',
  DATA_REVIEW_SET: 'Data Review Set',
  DATA_REVIEW_SET_SAVED_SUCCESSFULLY: 'Data Review Set saved successfully',
  DATA_REVIEW_SET_UPDATED_SUCCESSFULLY: 'Data Review Set updated successfully',
  DATA_REVIEW_SUMMARY: 'Data Review Summary',
  DATA_REVIEW_SUMMARY_PLEASE_SELECT_FILTERS: 'Please select a study and a date range by using the Study and Data Update Range filters to the left.',
  DATA_REVIEW_SUMMARY_DATA_ERROR: 'Failed to get summary data for data review set',
  DATA_REVIEW_SUMMARY_FILTER_EXPLANATION: 'To see the listing details of a subject, please select a single subject by using the Subject filter to the left.',
  DATA_REVIEW_SUMMARY_FILTER_REVIEW_ROLES: 'Please select your review role to enable data review.',
  DATA_REVIEW_TRANSACTIONS: 'Review Set Transactions',
  DATA_REVIEW_UPDATE_TYPES_DISPLAY: function (updateType) {
    switch (updateType) {
      case ExposureAppConstants.DATA_REVIEW_UPDATE_TYPES.NEW:
        return 'new';
      case ExposureAppConstants.DATA_REVIEW_UPDATE_TYPES.UPDATED:
        return 'updated';
      case ExposureAppConstants.DATA_REVIEW_UPDATE_TYPES.DELETED:
        return 'deleted';
      case ExposureAppConstants.DATA_REVIEW_UPDATE_TYPES.NONE:
        return 'no change';
      default:
        return 'N/A';
    }
  },
  DATA_SELECTOR: 'Data selector',
  DATE: 'Date',
  DATE_TIME: 'Date/Time',
  // keep in sync with the backend: ChronosActor#defaultJobSchedule
  DEFAULT_METRIC_GROUP_APPLIES_TO_ALL_STUDIES: 'Default Metric Group Applies to All Studies',
  DEFAULT_METRIC_GROUP_APPLIES_TO_ALL_STUDIES_EXCEPT: 'Default Metric Group Applies to All Studies Except:',
  DEFAULT_MONITOR_SCHEDULE: 'R/2016-01-01T09:00.000Z/P1D',
  DEFINE_DRILLDOWN_OPTIONS: 'Define drilldown options for analytics',
  DEFINE_NEW_REPORT: 'Define new analytics',
  DELETE: 'Delete',
  DELETE_METRIC_GROUP: 'Delete Metric Group',
  DESCENDING_ORDER: function (label) {
    return `${label} (Descending)`;
  },
  DISABLE: 'Disable',
  ENABLE: 'Enable',
  DISPOSITION_PAGE_TITLE: 'Disposition Event Configuration',
  DISPOSITION_UNCONFIGURED_TITLE: 'Unconfigured Customer Events',
  DISPOSITION_CONFIGURED_TITLE: 'Configured Customer Events',
  DISPOSITION_COLUMN_SEQ: 'Sequence',
  DISPOSITION_COLUMN_UI_EVENT: 'Disposition Label in the UI',
  DISPOSITION_COLUMN_USDM_EVENT: 'USDM Disposition Event',
  DISPOSITION_COLUMN_CUSTOMER_EVENT: 'Customer Disposition Event',
  DISPOSITION_COLUMN_IS_STARTING_EVENT: 'First event',
  DISPOSITION_COLUMN_STATE: 'State',
  DISPOSITION_COLUMN_STATE_ACTIVE: 'Active',
  DISPOSITION_COLUMN_STATE_WITHDRAWN: 'Withdrawn',
  DISPOSITION_COLUMN_STATE_COMPLETED: 'Completed',
  DISPOSITION_COLUMN_ENABLE: 'Enabled',
  DISPOSITION_WARNING_DELETE_HEADER: 'Are you sure you want to delete this disposition?',
  DISPOSITION_WARNING_DELETE_CONTENT: 'If you delete this entry the disposition order might change',
  DISPLAY_MULTIPLIER: 'Display Multiplier',
  DISPLAY_NAME: 'Display Name',
  DISPLAY_ORDER: 'Display Order',
  DELETE_ACTION_IS_IRREVERSIBLE: 'The delete action is irreversible.',
  DELETE_INHERIT_NOTE: function (isMultipleUsers) {
    return `As an account administrator, you will inherit the following shared files and tasks owned by or assigned to the user${isMultipleUsers ? 's' : ''} you are deleting.`;
  },
  DELETE_IF_OWNER: 'Delete, if owner',
  DELETE_DATA_ACCESS_GROUPS_SUCCESS: function (groupCount) {
    return `You have successfully deleted ${groupCount} data access group${groupCount > 1 ? 's' : ''}.`;
  },
  DELETE_DATA_REVIEW_ROLES_SUCCESS: function (roleCount) {
    return `You have successfully deleted ${roleCount} data review role${roleCount > 1 ? 's' : ''}.`;
  },
  DELETE_CONFIGURATION: 'Delete Configuration',
  DELETE_USERS_WILL_PREVENT_ACCESS: function (numUsers) {
    return `Deleting the following ${numUsers > 1 ? numUsers + ' users' : 'user'} will prevent them from accessing the account. Their permissions on this account will be removed.`;
  },
  DELETE_OVERSIGHT_SCORECARD_CONFIG_SUCCESSFUL: 'Oversight scorecard metric configuration deleted successfully',
  DELETING_CONDITIONAL_FILTERS: 'Deleting conditional filters',
  DELETING_REPORTS_REMOVE_FROM_DASHBOARDS: {
    singular: 'Deleting this analytics will remove this analytics from all dashboards.',
    plural: 'Deleting these analytics will remove these analytics from all dashboards.',
  },
  DENOMINATOR_LABEL: 'Denominator Label',
  DESCRIPTION: 'Description',
  DESCRIPTION_CANNOT_BE_EMPTY: 'Description cannot be empty.',
  DESCRIPTION_REQUIRED: 'Description (required)',
  DETAILS: 'Details',
  DIRECTIONALITY: 'Directionality',
  DISCARD: 'Discard',
  DISCARD_CHANGES: 'Discard Changes?',
  DISCARD_CHANGES_TO_DASHBOARD: 'Discard Changes to Dashboard?',
  DISCARD_CHANGES_TO_DATA_ACCESS_GROUP_ASSIGNMENT: 'Discard Changes to Data Access Groups Assignment?',
  DISCARD_CHANGES_TO_MONITOR: 'Discard Changes to Monitor?',
  DISCARD_CHANGES_TO_REPORT: 'Discard Changes to Analytics?',
  DISCARD_CHANGES_TO_TASK: 'Discard Changes to Task?',
  DISCARD_CHANGES_TO_TEMPLATE: 'Discard Changes to Template?',
  DONE: 'Done',
  DOWNLOAD: 'Download',
  DOWNLOAD_CSV: 'Download a CSV',
  DOWNLOAD_PDF: 'Download a PDF',
  DRILLDOWN_OPTIONS: 'Drilldown options',
  DRILLDOWN_SELECTION_LIMIT_EXCEED: 'Exceeed data point selection limit of 500.',
  DRILL_TARGETS: 'Drill Targets',
  DROPDOWN: 'Dropdown',
  DROPDOWN_SELECT_PLACEHOLDER: 'Select',
  DUE_DATE: 'Due date',
  DUE_DATE_CANNOT_BE_IN_THE_PAST: 'Due date cannot be in the past.',
  DUE_DATE_REQUIRED: 'Due Date (required)',
  DUPLICATE_ACCOUNT_WITH_IDP: (accountId) => `This user already belongs account ${accountId} with IdP set`,
  DUPLICATE_SESSION_FILTER: 'A session filter with this configuration already exists.',
  DUPLICATE_USER: 'This user already exists in the current account',
  DYNAMIC: 'Dynamic',
  DYNAMIC_FILTER: function (id) {
    return `Dynamic filter ${id}`;
  },
  DYNAMIC_FILTERS: 'Dynamic Filters',
  DYNAMIC_FILTERS_DIFFERENT_SCHEMA: "Unable to apply dynamic filters to a dashboard which includes analytics from multiple Comprehend schemas.",
  DYNAMIC_FILTERS_DISCARDED_NO_SCHEMA: 'Dynamic filters discarded because no schema was selected.',
  DYNAMIC_FILTERS_DISCARDED_INVALID: 'Invalid dynamic filters discarded.',
  DYNAMIC_FILTERS_EMPTY_DASHBOARD: "Add analytics before adding dynamic filters.",
  DYNAMIC_FILTERS_INSTRUCTIONS: 'filters that analytics viewers can interact with to further refine the analytics data set.',
  DYNAMIC_FILTERS_TIP: "Select a column in the schema tree view and then click the 'Add Dynamic Filter' button.",
  EDIT: 'Edit',
  EDIT_ASSIGNEES: 'Edit assignees',
  EDIT_CHILDREN: 'Edit children',
  EDIT_CONDITIONAL_FILTER: 'Edit Conditional Filter',
  EDIT_DASHBOARD: 'Edit Dashboard',
  EDIT_DATA_ACCESS_GROUP: 'Edit Data Access Group',
  EDIT_DATA_REVIEW_ROLE: 'Edit Data Review Role',
  EDIT_DATA_REVIEW_SET: 'Edit Data Review Set',
  EDIT_DEFAULT_METRIC_GROUP: 'Edit Default Metric Group',
  EDIT_FILTER: 'Edit filter',
  EDIT_METRIC_GROUP: 'Edit Metric Group',
  EDIT_MONITOR: 'Edit Monitor',
  EDIT_MONITOR_DEFINITION: 'Edit Monitor Definition',
  EDIT_QUALITY_AGREEMENT: 'Edit Quality Agreement',
  EDIT_SHARING: 'Edit Sharing',
  EDIT_TABULAR_REPORT: 'Edit Tabular Analytics',
  EDIT_TEAM: 'Edit Team',
  EDIT_TEMPLATE: 'Edit Template',
  EDIT_TEMPLATE_ADVANCED_REPORT: 'Edit Advanced Analytics',
  EDIT_TEMPLATE_SUCCESSFUL: 'Status update: Edit template succeeded.',
  EDIT_TEMPLATE_UNSUCCESSFUL: 'Status update: Edit template was unsuccessful.',
  EM_DASH: '\u2014',
  EMAIL: 'Email',
  EMAIL_FORMATS_ARE_INVALID: 'Email formats are invalid. Users with invalid email formats cannot be added.',
  ENABLED: 'Enabled',
  ENTER_CQL: 'Enter CQL',
  ENTER_CQL_OR_BROWSE: 'Enter CQL or browse',
  ENTER_EMAIL_ADDRESS: 'Enter your email address',
  ENTITY: 'Entity',
  ENTITY_SCORE: 'Entity Score [0-10]',
  ENTITY_SEARCHER_PLACEHOLDER: 'Start typing to find relevant content',
  ENTITY_SEARCHER_PLACEHOLDER_VA: 'Ask DaLIA...',
  ENTITY_SEARCHER_TOOLTIP: 'Search for relevant content',
  ERROR_NOT_FOUND: 'File not found.',
  ERROR_SAVING_DATA_REVIEW_SET: 'Error saving data review set - errors found on the following listings:',
  ERROR_TEAMS_NOT_FOUND: 'Teams not found.',
  ERROR_UNABLE_TO_RESOLVE: 'ERROR! Unable to resolve',
  // TODO: Detect the browser type and version to display the correct format for the user.
  ERROR_URL_QUERY: 'There is an error in the URL query parameters.',
  ERROR_USERS_NOT_FOUND: 'Users not found.',
  EXCLUDE_NULL_VALUES: 'Exclude null values',
  EXCLUDE_NULL_VALUES_FOOTNOTE: '= Null values are excluded',
  EXPORT: 'Export',
  EXPORT_OPTIONS: 'Export Options',
  EXTENDED_TASK_ADDED: 'Extended task attribute added',
  EXTENDED_ATTRIBUTES: 'Extended Attributes',
  FAIL: 'Fail',
  FAIL_TO_DELETE: 'Fail to delete.',
  FAIL_UPDATE_TASK: 'Fail to update task.',
  FAILED_CREATE_TASK: 'Failed to create task.',
  FAIL_IMPORT_REVIEW_FILE: 'An invalid file was uploaded, no review has been registered - please import a valid file',
  FAILED_NEW_PASSWORD_SAME_AS_PREVIOUS_ONE: 'New password cannot be the same as the previous password.',
  FAILED_TO_ADD_NEW_METRIC_GROUP: 'Failed to add new metric group.',
  FAILED_TO_DELETE_METRIC_GROUP: 'Failed to delete metric group',
  FAILED_TO_EDIT_METRIC_GROUP: 'Failed to edit metric group',
  FAILED_TO_GET_DATA_FROM_SERVER: 'Failed to get Data from server.',
  FAILED_TO_GET_FILTER_DATA_FROM_SERVER: 'Failed to get filter data from server.',
  FAILED_TO_GET_REVIEW_SETS_FOR_SUMMARY: 'Failed to get Data Review Sets',
  FAILED_TO_GET_REPORT_NAMES_FOR_SUMMARY: 'Failed to get report names',
  FAILED_USER_REGISTRATION_REQUEST: 'Sign up failed, please refresh the page and try again.',
  FAVORITE_ONLY: 'Favorite only',
  FAVORITES: 'Favorites',
  FILES_ASSOCIATE_WITH_TASK_CANNOT_BE_DELETED: {
    singular: 'The following item cannot be deleted because it has the following open tasks associated with it:',
    plural: 'The following items cannot be deleted because they have the following open tasks associated with them:',
  },
  FILES_ASSOCIATE_WITH_RACT_CANNOT_BE_DELETED: {
    singular: 'The following item cannot be deleted because it is associated with RACT:',
    plural: 'The following items cannot be deleted because they are associated with RACT:',
  },
  // Used for messages such as `3 files have been successfully deleted!`.
  FILES_DELETED: {
    singular: 'file has been successfully deleted!',
    plural: 'files have been successfully deleted!',
  },
  FILES_MOVED: function (filesConunt) {
    return `${filesConunt} file(s) ${filesConunt > 1 ? 'have' : 'has'} been successfully moved!`;
  },
  ITEMS_CANNOT_BE_MOVED: {
    singular: 'Item that cannot be moved',
    plural: 'Items that cannot be moved',
  },
  FILTER: 'Filter',
  FILTERS: 'Filters',
  FILTER_HAS_BEEN_REPLACED_BY_TASK_FILTERS: 'The study filter has been replaced by filters associated with current task.',
  FILTER_TYPE: 'Filter Type',
  FILTER_MODE_CQL: 'Or select a column from the table',
  FILTER_MODE_DATA_PICKER: 'Or enter CQL directly',
  FILTER_NOT_APPLICABLE: 'Filter not applicable to this analytics',
  FILTER_NOT_APPLICABLE_MASTER_FILTER: 'Filter not applicable',
  FIRST_NAME: 'First name',
  FOCUS_TAGS: "Tags",
  FOLDER: 'Folder',
  FOLDER_TITLE_CANNOT_BE_EMPTY: 'Folder title cannot be empty.',
  FOLDER_TITLE_DUPLICATE: 'Same folder title already exists.',
  FOLDER_TITLE_INVALID_CHARS: 'Folder title cannot be empty or contain more than 100 characters.',
  FOLDER_TITLE_UPDATED_TO: function (newTitle) {
    return `Folder name has been updated to ${newTitle}.`;
  },
  FOLDERS_CANNOT_BE_DELETED: {
    singular: 'Folder that cannot be deleted',
    plural: 'Folders that cannot be deleted',
  },
  FOLDERS_NOT_EMPTY_TO_DELETE: {
    singular: 'You cannot delete the following folder because it is not empty:',
    plural: 'You cannot delete the following folders because they are not empty',
  },
  FORMAT: 'Format',
  FORMULA: 'Formula',
  FROM: 'From',
  FROM_DATE: 'From Date',
  FUTURE_ONLY: 'Future only',
  GENERATE_FRAME: 'Generate Frame',
  GET_STARTED: 'Get started',
  GO_TO_LOGIN: 'Go to login',
  GRAPHICAL_REPORT_FAILED_TO_PARSE_VIZ_SPEC: 'Failed to parse viz spec.',
  GRAPHICAL_REPORT_FAILED_TO_PARSE_VIZ_SPEC_MUST_BE_AN_ARRAY: 'Failed to parse viz spec. Viz spec must be an array.',
  GRAPHICAL_REPORT_FAILED_TO_PROCESS_DATA: 'Failed to process data.',
  GO_BACK: 'Go Back',
  GRAPHICAL_REPORT: 'Graphical Analytics',
  GRID_VIEW: 'Grid View',
  GROUP: 'Group',
  GROUP_PERMISSIONS: 'Group Permissions',
  GROUPS: 'Groups',
  HAS_BEEN_SAVED: function (name) {
    return `'${name}' has been saved.`;
  },
  HELP: 'Help',
  HIGH_THRESHOLD: 'High Threshold',
  HISTORY: 'History',
  HOME_PAGE_ADMIN: 'Configure Home page',
  HOME_PAGE_EDITOR: 'Configure My Home Page',
  HOME_PAGE_NOT_CONFIGURED: 'Home page has not been configured.',
  HOME_PAGE_TAB_UNAVAILABLE: 'Report is not available',
  HOME_PAGE_TAB_UNAVAILABLE_DETAILS: 'Report is not accessible anymore or was removed',
  HTML: 'HTML',
  HTML_TIP: "Define HTML to render highchart. CAUTION: Don't use the abbreviated <div /> html form as it will not render properly.",
  IF_UNABLE_TO_GRANT_OR_REVOKE: "If you're unable to grant or revoke certain permissions, it could be due to one of multiple reasons.",
  IF_UNABLE_TO_GRANT_OR_REVOKE_BULLET_1: 'Either you do not, or the recipient does not have the specific sharing permission enabled at the account level.',
  IF_UNABLE_TO_GRANT_OR_REVOKE_BULLET_2: 'The user is member of a team and cannot have all their sharing permissions removed at the individual level.',
  IF_UNABLE_TO_GRANT_OR_REVOKE_BULLET_3: "The user's permission was granted as part of a team and can only be removed at the team level.",
  IF_UNABLE_TO_GRANT_OR_REVOKE_BULLET_4: "The user's permission to this item was inherited from the item's parent folder and can only be removed at the folder level.",
  IF_UNABLE_TO_GRANT_OR_REVOKE_BULLET_5: "The item has already been shared with the user through a containing dashboard. Sharing access to this item can only be removed by removing access to the dashboard.",

  IF_YOU_DONT_SAVE_CHANGES_WILL_BE_LOST: "If you don't save, changes will be lost.",
  IF_YOU_LEAVE_NOW_CHANGES_WILL_BE_LOST: "If you leave now, all changes will be lost.",
  IGNORE_DENOMINATOR: 'Ignore Denominator',
  IMPACT_RANGE: 'Impact range',
  INACTIVE: 'Inactive',
  INCLUDED: 'Included',
  INDICATION: 'Indication',
  INFORMATION: 'Information',
  INHERIT: 'Inherit',
  INHERIT_ITEMS: 'Inheriting the following item(s):',
  INSUFFICIENT_PERMISSIONS: 'Insufficient Permissions',
  INVALID_CQL: 'Invalid CQL. Please check your entry.',
  INVALID_DATA_FRAME_JSON: 'Invalid Data Frame JSON',
  INVALID_DATA_REVIEW_ROLE_NAME_LENGTH: 'Invalid Data Review Role Name: Please enter a name between 1 and 100 characters in length',
  INVALID_EMAIL: 'This is an invalid email',
  INVALID_JSON: 'Invalid JSON',
  INVALID_MONITOR_CONFIGURATION_JSON: 'Invalid Monitor Configuration JSON',
  INVALID_NAME: 'Invalid name',
  INVALID_SCHEMA: 'Invalid schema',
  INVALID_MESSAGE: function (name) {
    return `${name} is Mandatory.`;
  },
  INVESTIGATOR: 'Investigator',
  INVITATION: 'invitation',
  ITEM_ALREADY_IN_DESTINATION: 'The item is already in this destination.',
  ITEMS_ALREADY_IN_DESTINATION: 'The items are already in this destination.',
  ITEMS_CANNOT_BE_DELETED: {
    singular: 'Item that cannot be deleted',
    plural: 'Items that cannot be deleted',
  },
  KPI_STUDIO: 'KPI Studio',
  LAST_NAME: 'Last name',
  LAST_USER_UPDATE: 'Last user update',
  LAST_RUN: 'Last run',
  LEGACY_ACCOUNT: 'Legacy Account?',
  LEGEND: 'Legend',
  LESS: 'Less',
  LINK_EXPIRED: function (linkType) {
    return `The ${linkType} link has expired.`;
  },
  LINK_ONLY_VALID_FOR_X_TIME: function (linkType, millis) {
    return `Your ${linkType} link is only valid for ${humanizer(millis)}.`;
  },
  LINK_TASK_TO_A_DASHBOARD_REPORT: 'Link task to a dashboard/analytics',
  LINKED_REPORT_DASHBOARD: 'Linked analytic/dashboard',
  LIVE_REPORT: 'Live Report',
  LOADING_WITH_THREE_DOTS: 'Loading...',
  LOCKED: 'Locked',
  LOGIN_FORGOT_PASSWORD: 'Reset password',
  LOW_THRESHOLD: 'Low Threshold',
  MANAGE_GROUP_ASSIGNMENT: 'Manage Group Assignment',
  MANAGE_ASSIGNEES: 'Manage assignees',
  MAXIMUM: 'Maximum',
  MARK_AS_REVIEWED: 'Mark as Reviewed',
  MEAN: 'Mean',
  MEDIAN: 'Median',
  METRIC: 'Metric',
  METRIC_CANNOT_BE_EMPTY: 'Metric cannot be empty.',
  METRIC_GROUP: 'Metric Group',
  METRIC_GROUP_APPLIES_TO_STUDIES: function (numStudies) {
    return `Metric Group Applies to Stud${numStudies > 1 ? 'ies' : 'y'}:`;
  },
  METRIC_ID: 'Metric ID',
  METRIC_WEIGHTS: 'Metric weights',
  METRICS: 'Metrics',
  METRICS_HAVENT_BEEN_CONFIGURED: 'Metrics for this account haven\'t been configured yet',
  METRIC_CONFIGURATION: 'METRIC CONFIGURATION',
  MINIMUM: 'Minimum',
  MISSING_PROPERTY: 'Missing Property',
  MISSING_PROPERTIES: 'Missing Properties',
  MITIGATION_PROGRESS: 'Mitigation Progress',
  MODIFICATION_NOTE: 'Modification Note',
  MODIFICATION_NOTE_IS_REQUIRED: 'Modification Note is required.',
  MODIFICATION_NOTE_PLACEHOLDER: "Please describe the changes you're making to this monitor.",
  MODIFICATION_NOTES: "Modification Notes",
  MODULES: "Modules",
  MONITOR: 'Monitor',
  MONITOR_CONFIGURATION: 'Monitor Configuration',
  MONITOR_DATA_FRAME_IS_REQUIRED: 'Data Frame is required.',
  MONITOR_DOWNLOAD_HISTORY_TEXT: 'of all configuration edits for this data monitor.',
  MONITOR_EXEC_PLAN: 'Monitor Execution Plan',
  MONITOR_EXEC_PLAN_HELP_DETAILS: 'Monitor Execution Plan Help Details',
  MONITOR_EXEC_PLAN_IS_REQUIRED: 'Execution Plan is required.',
  MONITOR_FAILED_TO_GENERATE_DATA_FRAME: 'Failed to generate data frame.',
  MONITOR_HAS_BEEN_RUN_CANNOT_MODIFY_METRIC_DEFINITION: 'Monitor has been run. Metric definition cannot be modified.',
  MONITOR_HAS_BEEN_RUN_CANNOT_MODIFY_TABLE_REFERENCE: 'Monitor has been run. Table reference cannot be modified.',
  MONITOR_METRIC_IS_REQUIRED: 'Metric is required.',
  MONITOR_METRIC_QUERY_IS_INVALID: 'Metric query is invalid.',
  MONITOR_METRIC_QUERY_IS_REQUIRED: 'Metric query is required.',
  MONITOR_METRIC_REFERENCE_NAME_IS_REQUIRED: 'Metric reference name is required.',
  MONITOR_METRIC_REFERENCE_NAME_MUST_BE_UNIQUE: 'Metric reference name must be unique.',
  MONITOR_METRIC_SCALE_FACTORS_MUST_BE_NUMERIC: 'Metric scale factors must be numeric.',
  MONITOR_NAME_IS_REQUIRED: 'Monitor name is required.',
  MONITOR_OWNER_TASK: {
    PLEASE_NOTE: 'Please note, by default the data monitor ',
    OWNER: 'owner ',
    BECOMES_THE_ASSIGNEE: 'becomes the task assignee if no one else qualifies to receive the task (due to filters).',
  },
  MONITOR_PREVIEW_ERROR: 'There was a system error retrieving data for the visualization',
  MONITOR_PREVIEW_LOADING_MESSAGE: 'Re-calculating and re-rendering. This process may take up to a few minutes.',
  MONITOR_PREVIEW_TIMED_OUT: 'There was a system error rendering the visualization and the process has timed out.',
  MONITOR_RESULT: 'Monitor Result',
  MONITOR_SCHEDULE_TOOLTIP_MESSAGE: 'The monitor will run on this schedule.',
  MONITOR_STATE: 'Monitor State',
  MONITOR_STATUS: 'Monitor status',
  MONITOR_STATUS_ACTIVE_TOOLTIP_MESSAGE: 'When a data monitor is active, it performs scheduled runs and generates tasks upon a threshold breach.',
  MONITOR_STATUS_INACTIVE_TOOLTIP_MESSAGE: 'When a data monitor is inactive, it does not perform scheduled runs and does not generate tasks upon a threshold breach.',
  MONITOR_STATUS_RECORDING_TOOLTIP_MESSAGE: 'When a data monitor is recording, it performs scheduled runs and does not generate tasks upon a threshold breach.',
  MONITOR_TAB_DISPLAY_NAME: {
    [ExposureAppConstants.MONITOR_TABS.OVERVIEW]: 'Overview',
    [ExposureAppConstants.MONITOR_TABS.CONFIGURATION]: 'Configuration',
  },
  MONITOR_TABLE_IS_NOT_IN_SELECTED_SCHEMA: 'Table reference cannot be found in the selected schema.',
  MONITOR_TABLE_IS_REQUIRED: 'Monitor table reference is required.',
  MONITOR_THRESHOLD_SCALE_FACTOR_MUST_BE_NUMERIC: 'Threshold scale factor must be numeric.',
  MONITOR_THRESHOLD_TYPE: 'Threshold Type',
  MORE: 'More',
  MOVE: 'Move',
  MOVE_IMPACT_SHARING: `Please note that you are moving an item(s) TO or FROM a shared location.
    This will change which users/teams have access to the item(s) and their permissions.`,
  MOVE_MONITOR_MODIFICATION_NOTE: function (oldFolder, newFolder) {
    return `Moved from folder '${oldFolder}' to folder '${newFolder}'.`;
  },
  MY_DASHBOARDS: 'My Dashboards',
  MY_HOME: 'My Home',
  MY_PROFILE: 'My Profile',
  NAME: 'Name',
  NAME_OF_REVIEWER: 'Name of Reviewer',
  NEW_QUERY: 'New query',
  NEXT: 'Next',
  NEXT_PAGE: 'Next Page',
  NO_APPLIED_FILTERS: 'No applied filters.',
  NO_ASSOCIATED_REPORT_OR_DASHBOARD: 'No Associated Analytics or Dashboard',
  NO_DATA_AVAILABLE: 'No data available',
  NO_DATA_RETURNED: 'No data returned.',
  NO_FILTERS_FOR_THIS_FILE: function (fileType) {
    return `No included filters for this ${(convertReportToAnalytics(fileType) || 'file').toLowerCase()}.`;
  },
  NO_FILTERS_YET: 'No filters yet.',
  NO_INVITATIONS_SENT: 'No invitations sent',
  NO_LONGER_FOLLOW_TASK: "By assigning another user, you will no longer be able to follow this task. Please add yourself as an observer before doing so, if you'd like to continue following the task.",
  NO_METRICS_SELECTED: 'No metrics selected, configuration is empty.',
  NO_QUALITY_AGREEMENT_CONFIGURED_FOR_STUDY: 'No quality agreement configured for this Study & CRO selection.',
  NO_QUALITY_AGREEMENT_CONFIGURED: 'No quality agreement is configured.',
  NO_QUALITY_AGREEMENT_CONFIGURED_FOR_THIS_SELECTION: 'No quality agreement configured for this selection.',
  NO_STUDIES_ASSOCIATED_WITH_METRIC_GROUP: 'No studies are associated with this metric group',
  NO_TEMPLATES: 'No templates.',
  NON_BREACH: 'Non-breach',
  NONE: 'None',
  NONE_AT_THIS_TIME: 'None at this time.',
  NOT_APPLICABLE: 'Not Applicable',
  NOT_AVAILABLE: 'Not Available',
  NOT_AVAILABLE_ABBREVIATION: 'N/A',
  NOT_SELECTED: 'Not Selected',
  NOT_URGENT: 'Not urgent',
  NULL: 'Null',
  NUMERATOR_LABEL: 'Numerator Label',
  NUMERIC_VALUES_ONLY: 'Numeric values only.',
  NUMBER_REVIEWED_RECORDS: 'Number of reviewed records by DLL',
  OBSERVER: 'Observer',
  OBSERVERS: 'Observers',
  OBSERVED_BY_ME:'Observed by me',
  OBJECT_UNIQUE_KEY: 'Object Unique Key',
  OK: 'OK',
  OKAY: 'Okay',
  ONLY_DASHBOARD_REPORTS_OR_MONITORS_CAN_BE_MOVED_AT_THIS_TIME: 'Only dashboard analytics or monitors can be moved at this time.',
  ONLY_ONE_FOLDER_CAN_BE_RENAMED_AT_THIS_TIME: 'Only one folder can be renamed at this time.',
  OPEN: 'Open',
  OPEN_TASK: 'Open task',
  OPEN_TASKS(count) {
    return `${count} Open tasks`;
  },
  OPTIONAL: 'Optional',
  OPTIONAL_LOWER_CASE_WITH_PAREN: ' (optional)',
  OR_SAVE_AND_EXIT: 'or save & exit',
  ORGANIZATION_ROLE: 'Role at organization',
  OTHER: 'Other',
  OVERSIGHT_ENROLLED: (enrollmentCount) => `${enrollmentCount} enrolled`,
  OVERSIGHT_ENROLLMENT_AND_ACTIVATION_DETAILS: (enrollmentCount, targetEnrollment, sitesActivated, targetActivations) => {
    return `${enrollmentCount}/${targetEnrollment} enrolled, ` +
      `${sitesActivated}/${targetActivations} sites activated`;
  },
  OVERSIGHT_DURATION_DETAILS: (studyStartDate, plannedEndDate) => `Start: ${studyStartDate}, End: ${plannedEndDate}`,
  OVERSIGHT_PHASE_DETAILS: (therapeuticArea, phase) => `${therapeuticArea} Phase ${phase}`,
  OVERSIGHT_METRIC: 'metric',
  OVERSIGHT_METRICS: 'metrics',
  OVERSIGHT_METRICS_ALL: 'All',
  OVERSIGHT_METRICS_APPLY: 'Apply',
  OVERSIGHT_METRICS_CATEGORIES: 'Categories',
  OVERSIGHT_METRICS_CATEGORY_NAME: 'Metrics',
  OVERSIGHT_METRICS_CLEAR: 'Clear',
  OVERSIGHT_METRICS_SELECT_ALL: 'Select All',
  OVERSIGHT_SCORECARD: 'Oversight Scorecard',
  OVERSIGHT_SCORECARD_ACCESS: 'Oversight Scorecard Access',
  OVERSIGHT_SCORECARD_MODULE: 'Oversight Scorecard',
  RACT_MODULE: 'RACT',
  RBQM_MODULE: 'RBQM',
  OVERSIGHT_SCORECARD_FOCUS_AREA: 'Study Oversight',
  OVERSIGHT_SCORE_INVALID: 'Invalid',
  OVERSIGHT_SITE_ACTIVATION: (activationDate) => `Activated: ${activationDate}`,
  OVERSIGHT_GROUP_BY_NONE: 'None',
  OVERSIGHT_SCORE_CATEGORY: 'Overall Score Category',
  OVERSIGHT_SCORE_MISSING: 'Missing',
  OVERSIGHT_SCORE_UNKNOWN: 'Unknown',
  OVERSIGHT_TOOLTIP_CRITICAL: 'Critical',
  OVERSIGHT_TOOLTIP_INVALID_DATA: 'Metric value is invalid',
  OVERSIGHT_TOOLTIP_MISSING_DATA: 'Required data missing for this metric',
  OVERSIGHT_TOOLTIP_WARNING: 'Warning',
  OVERSIGHT_TOOLTIP_GOOD: 'Good',
  OVERSIGHT_TOOLTIP_MISSING: (nMissing, entity) =>
    `${nMissing} metric(s) omitted from ${entity} score:`,
  OVERSIGHT_TOOLTIP_LEGEND_BETWEEN: (value1, value2) => `Between ${value1} and ${value2}`,
  OVERSIGHT_TOOLTIP_LEGEND_GREATER: (value) => `Greater than ${value}`,
  OVERSIGHT_TOOLTIP_LEGEND_LESS: (value) => `Less than ${value}`,
  OVERSIGHT_TOOLTIP_STUDY_ID: 'Study ID',
  OVERSIGHT_TOOLTIP_STUDY_NAME: 'Study Name',
  OVERSIGHT_TOOLTIP_STUDY_VIEW_SITES: 'View Sites',
  OVERSIGHT_TOOLTIP_STUDY_DESCRIPTION: 'Description',
  OVERSIGHT_TOOLTIP_STUDY_PROGRAM: 'Program',
  OVERSIGHT_TOOLTIP_STUDY_THERAPEUTIC: 'Therapeutic Area',
  OVERSIGHT_TOOLTIP_STUDY_REGIONS: 'Regions',
  OVERSIGHT_TOOLTIP_STUDY_SPONSOR: 'Sponsor',
  OVERSIGHT_TOOLTIP_STUDY_CRO_NAMES: 'CRO',
  OVERSIGHT_TOOLTIP_STUDY_STATUS: 'Status',
  OVERSIGHT_TOOLTIP_STUDY_PHASE: 'Phase',
  OVERSIGHT_TOOLTIP_STUDY_MEDICAL_INDICATION: 'Indication',
  OVERSIGHT_TOOLTIP_STUDY_START_DATE: 'Study Start',
  OVERSIGHT_TOOLTIP_STUDY_ENROLLMENT: 'Enrollment',
  OVERSIGHT_TOOLTIP_STUDY_ENROLLMENT_VALUE: (actual, planned) => `${actual}/${planned} enrolled`,
  OVERSIGHT_TOOLTIP_STUDY_ACTUAL_ENROLLMENT_COUNT: 'Actual enrollment count',
  OVERSIGHT_TOOLTIP_STUDY_PLANNED_ENROLLMENT_COUNT: 'Planned enrollment count',
  OVERSIGHT_TOOLTIP_STUDY_SITE_ACTIVATION: 'Sites',
  OVERSIGHT_TOOLTIP_STUDY_SITE_ACTIVATION_VALUE: (actual, planned) => `${actual}/${planned} activated`,
  OVERSIGHT_TOOLTIP_STUDY_CURRENT_SITE_ACTIVATION_COUNT: 'Current site activation count',
  OVERSIGHT_TOOLTIP_STUDY_TARGET_SITE_ACTIVATION_COUNT: 'Target site activation count',
  OVERSIGHT_TOOLTIP_STUDY_CURRENT_MILESTONE: 'Current milestone',
  OVERSIGHT_TOOLTIP_STUDY_CURRENT_MILESTONE_VALUE: (milestone, date) => `${milestone}, End Date: ${date} (forecast)`,
  OVERSIGHT_TOOLTIP_STUDY_CURRENT_MILESTONE_PLANNED_DATE: 'Current milestone planned date',
  OVERSIGHT_TOOLTIP_STUDY_CURRENT_MILESTONE_PROJECTED_DATE: 'Current milestone projected date',
  OVERSIGHT_TOOLTIP_STUDY_PLANNED_END_DATE: 'Study End',
  OVERSIGHT_TOOLTIP_STUDY_PLANNED_END_DATE_VALUE: (value) => `${value} (planned)`,
  OVERSIGHT_TOOLTIP_SITE_TITLE_VALUE: (id, name) => `Site ${id}: ${name}`,
  OVERSIGHT_TOOLTIP_SITE_LOCATION: 'Location',
  OVERSIGHT_TOOLTIP_SITE_LOCATION_VALUE: (city, state, postal) => `${city}, ${state} ${postal}`,
  OVERSIGHT_TOOLTIP_SITE_ID: 'Site ID',
  OVERSIGHT_TOOLTIP_SITE_NAME: 'Site Name',
  OVERSIGHT_TOOLTIP_SITE_CRA_NAME: 'CRA',
  OVERSIGHT_TOOLTIP_SITE_CRO_NAME: 'CRO',
  OVERSIGHT_TOOLTIP_SITE_INVESTIGATOR_NAME: 'Investigator',
  OVERSIGHT_TOOLTIP_SITE_POSTAL: 'Postal',
  OVERSIGHT_TOOLTIP_SITE_CITY: 'City',
  OVERSIGHT_TOOLTIP_SITE_REGION: 'Region',
  OVERSIGHT_TOOLTIP_SITE_STATE: 'State',
  OVERSIGHT_TOOLTIP_SITE_COUNTRY: 'Site Country',
  OVERSIGHT_TOOLTIP_SITE_ACTIVATION_DATE: 'Activation date',
  OVERSIGHT_TOOLTIP_SITE_DEACTIVATION_DATE: 'Deactivation date',
  OVERSIGHT_TOOLTIP_SITE_ENROLLED_COUNT: 'Enrollment',
  OVERSIGHT_TOOLTIP_METRIC_VALUE: 'Metric value',
  OVERSIGHT_TOOLTIP_METRIC_WEIGHT: 'Metric weight',
  OVERSIGHT_TOOLTIP_METRIC_MORE: 'More information',
  OVERSIGHT_TOOLTIP_SITE_FPFV: 'FPFV',
  OVERSIGHT_TOOLTIP_SITE_STATUS: 'Site Status',
  OVERSIGHT_TOOLTIP_PI_EMAIL: 'PI Email',
  OVERSIGHT_CONFIGURATION_BAND_IS_GOOD: 'Band is good',
  OVERSIGHT_CONFIGURATION_HIGH_IS_GOOD: 'High is good',
  OVERSIGHT_CONFIGURATION_LOW_IS_GOOD: 'Low is good',
  OVERVIEW: 'Overview',
  OWNER: 'Owner',
  PAGES: 'Pages',
  PARAMETER_IS_REQUIRED: 'Parameter is required',
  PARAMETER_MUST_BE_BOOLEAN: 'The value of the parameter must be a boolean.',
  PARAMETERS: 'Parameters',
  PARTIAL_INVITATIONS_SENT: 'Partial invitations sent',
  PASSWORD: 'Password',
  PASSWORD_AND_CONFIRM_PASSWORD_NOT_MATCH: 'Password and confirm password fields must match.',
  PASSWORD_REQUIREMENTS_ARRAY: [
    'Must be between 10 and 72 characters.',
    'Must contain 3 of the following types: uppercase letters, lowercase letters, numbers, and special characters',
    'Cannot contain your email or name.',
  ],
  PASSWORD_REQUIREMENTS_RESET_ARRAY: [
    'Cannot be the same as your previous password.',
  ],
  PASSWORD_RESET: 'Password Reset',
  PASSWORD_RESET_CONFIRM_MESSAGE: 'Your password has been reset!',
  PASSWORD_RESET_LINK_VALID_FOR: function (millis) {
    return `The reset password link will only be valid for ${humanizer(millis)}. Please contact your designated technical contacts for further support.`;
  },
  PASSWORD_RESET_AN_EMAIL_HAS_BEEN_SENT: 'Thank you. You should be receiving an email shortly.',
  PERFORMANCE: 'Performance',
  PENDO_BLOCKED: 'Some LSAC features may not function properly when a browser adblocker is enabled. ' +
    'Please disable your adblocker for ',
  PHONE_NUMBER: 'Phone number',
  PLEASE_ACCESS_THIS_APPLICATION_ON_A_DESKTOP_TO_VIEW_FULL_CONTENT: 'Please increase window size or, if on mobile, access this application on desktop to view full content.',
  PLEASE_COMPLETE_REGISTRATION_FORM: 'Please complete the account sign up process.',
  PLEASE_CONFIRM_DELETE: 'Please confirm you want to delete.',
  PLEASE_CONFIRM_IMPORT: 'Please confirm import',
  PLEASE_CONFIRM_MOVE: 'Please confirm you would like to move the item(s).',
  PLEASE_CONFIRM_YOU_WOULD_LIKE_TO_CONTINUE: 'Please confirm you would like to continue.',
  PLEASE_CONTACT_ADMIN: 'Please contact your administrator for further support.',
  PLEASE_CORRECT_ALL_ERRORS_ON_THE_PAGE_TO_PROCEED: 'Please correct all errors on the page to proceed.',
  PLEASE_DESCRIBE_THE_EDITS_YOU_HAVE_MADE: 'Please describe the edits you have made.',
  PLEASE_ENTER_ALL_PARAMETERS_BEFORE_RENDERING_PREVIEW: 'Please enter all parameters before rendering a preview.',
  PLEASE_ENTER_EMAIL_FOR_PASSWORD_RESET: 'Please enter your email to request a password reset link.',
  // TODO: Detect the browser type and version to display the correct format for the user.
  PLEASE_ENTER_VALID_DATE: 'Please enter valid date (ex: 2015-12-24 or 12/24/2015 based on your browser).',
  PLEASE_ENTER_VALID_EMAIL: 'Please enter a valid email address',
  PLEASE_MAKE_A_SELECTION: 'Please make a selection',
  PLEASE_NOTE: 'Please note:',
  PLEASE_SELECT_A_DESTINATION: 'Please select a destination!',
  PLEASE_SELECT_A_SCHEMA_ABOVE_TO_PROCEED: 'Please select a schema above to proceed',
  PLEASE_SELECT_A_SCHEMA_TO_PROCEED: 'Please select a schema above to proceed',
  PLEASE_SELECT_A_SINGLE_COLUMN: 'Please select a single column.',
  PLEASE_SELECT_A_SINGLE_STUDY_TO_VIEW_SITE_SCORECARD: 'Please select a single study to view the Site Scorecard.',
  PLEASE_SELECT_A_TABLE: 'Please select a table',
  PLEASE_SELECT_A_TABLE_COLUMN: 'Please select a table column before continuing.',
  PLEASE_SELECT_A_TASK_TYPE: 'Please select a task type',
  PLEASE_SELECT_AT_LEAST_ONE_DATA_ACCESS_GROUP_TO_DELETE: 'Please select at least one data access group to delete',
  PLEASE_SELECT_AT_LEAST_ONE_DATA_REVIEW_ROLE_TO_DELETE: 'Please select at least one data review role to delete',
  PLEASE_SELECT_AT_LEAST_ONE_FOLDER_REPORT_OR_DASHBOARD_TO_DELETE: 'Please select at least one folder, analytics or dashboard to delete.',
  PLEASE_SELECT_AT_LEAST_ONE_TEAM_TO_DELETE: 'Please select at least one team to delete.',
  PLEASE_SELECT_AT_LEAST_ONE_TEMPLATE_TO_DELETE: 'Please select at least one template to delete.',
  PLEASE_SELECT_AT_LEAST_ONE_USER_TO_DELETE: 'Please select at least one user to delete.',
  PLEASE_SELECT_FILES_TO_SHARE: 'Please select items to share.',
  PLEASE_SELECT_ONE_FOLDER_TO_RENAME: 'Please select one folder to rename.',
  PLEASE_SELECT_ONE_REPORT_DASHBOARD_OR_MONITOR_TO_MOVE: 'Please select only one item to move.',
  PLEASE_SPECIFY: 'Please specify',
  PRE_PROCESSING_FUNCTION_DEFINITION: 'Pre-Processing Function Definition',
  PRE_PROCESSING_FUNCTION_DEFINITION_TIP: 'Define the body for function(data) {}. Example: return data;',
  PREV: 'Prev',
  PREVIEW: 'Preview',
  PREVIOUS_PAGE: 'Previous Page',
  PRIVACY_POLICY_UPDATE: 'Privacy Policy Update',
  PRIVILEGE_TYPE_VIEW: 'View',
  PRIVILEGE_TYPE_EDIT: 'Edit',
  PROBLEMS_ADDING_USERS: 'There were problems adding the following users',
  PROBLEMS_TO_ACTIVATE_TAB: 'There were problems to activate tab, redirected to \'home/\'',
  PROCESSED_DATA: 'Processed Data',
  PROGRAM: 'Program',
  PRIORITY:'priority',
  QUALITY_AGREEMENT: 'Quality Agreement',
  QUALITY_AGREEMENT_CATEGORY: function (category) {
    switch (category) {
      case 'SUBJECT_ENROLLMENT':
        return 'Subject Enrollment';
      case 'SITE_PRODUCTIVITY':
        return 'Site Productivity';
      case 'SUBJECT_COMPLIANCE':
        return 'Subject Compliance';
      default:
        return 'Unknown Category';
    }
  },
  QUALITY_AGREEMENT_MUST_HAVE_ENABLED_KPI: 'At least one KPI must be enabled.',
  QUALITY_AGREEMENT_SAVED_SUCCESSFULLY: 'Quality Agreement saved successfully',
  QUALITY_AGREEMENT_THRESHOLD_VALUES_DIFFERENT_SIGNS: 'Threshold values must be either both positive numeric values or both negative numeric values',
  QUALITY_AGREEMENT_THRESHOLD_VALUES_INVALID: 'Max Variance Threshold % values must be greater than or equal to the Target Variance Threshold % values',
  QUALITY_AGREEMENT_UPDATED_SUCCESSFULLY: 'Quality Agreement updated successfully',
  QUALITY_AGREEMENT_VALUES_MUST_BE_NUMERIC: 'Quality Agreement plan and threshold values must be numeric.',
  QUERY: 'Query',
  QUERY_TIP: 'Double-click a column in the schema tree view to add its text to the query.',
  RACE: 'Race',
  RACT_STATUS: 'RACT Status',
  RACT_TOOLTIP_HIGH: 'High',
  RACT_TOOLTIP_MEDIUM: 'Medium',
  RACT_TOOLTIP_LOW: 'Low',
  RACT_TOOLTIP_RISK_SCORE_DESC: 'Auto calculated based on AVERAGE of all enabled Risk Category Scores',
  RACT_TOOLTIP_STUDY_CURRENT_MILESTONE_VALUE: (milestone, date) => `${milestone}, End Date: ${date} (forecast)`,
  RACT_TOOLTIP_STUDY_ENROLLMENT_VALUE: (actual, planned) => `${actual}/${planned} enrolled`,
  RACT_TOOLTIP_STUDY_SITE_ACTIVATION_VALUE: (actual, planned) => `${actual}/${planned} activated`,
  RACT_PROTOCOL_ID_EXISTS: 'Protocol ID Already exists.',
  RACT_ADD_NEW_STUDY_SUCCESS: 'Study is created and template assigned successfully',
  RACT_ADD_NEW_STUDY_ID_PLACEHOLDER: 'Study ID',
  RACT_ADD_NEW_STUDY_NAME_PLACEHOLDER: 'Study Name',
  RACT_ADD_NEW_PROTOCOL_ID_PLACEHOLDER: 'Protocol ID',
  RACT_ADD_NEW_PROGRAM_PLACEHOLDER: 'Program',
  RACT_ADD_NEW_SPONSOR_PLACEHOLDER: 'Sponsor Name',
  RACT_ADD_NEW_THERAPEUTIC_AREA_PLACEHOLDER: 'Therapeutic Area',
  RACT_ADD_NEW_INDICATION_PLACEHOLDER: 'Indication',
  RACT_ADD_NEW_START_DATE_PLACEHOLDER: 'Select Start Date',
  RACT_ADD_NEW_END_DATE_PLACEHOLDER: 'Select End Date',
  RACT_ASSIGN_TEMPLATE_PLACEHOLDER: 'Select Template',
  RACT_ADD_NEW_STUDY_NAME_ERROR_MESSAGE: 'Study name can\'t be empty.',
  RACT_ADD_NEW_PROTOCOL_ID_ERROR_MESSAGE: 'Protocol field can\'t be empty.',
  RACT_ADD_NEW_PROGRAM_ERROR_MESSAGE: 'Program can\'t be empty.',
  RACT_ADD_NEW_SPONSOR_ERROR_MESSAGE: 'Sponsor name can\'t be empty.',
  RACT_ADD_NEW_THERAPEUTIC_AREA_ERROR_MESSAGE: 'Therapeutic area can\'t be empty.',
  RACT_ADD_NEW_INDICATION_ERROR_MESSAGE: 'Indication can\'t be empty.',
  RACT_ADD_NEW_START_DATE_ERROR_MESSAGE: 'Study start date can\'t be empty.',
  RACT_ADD_NEW_END_DATE_ERROR_MESSAGE: 'Study end date can\'t be empty.',
  RACT_ASSIGN_TEMPLATE_ERROR_MESSAGE: 'Template field can\'t be empty.',
  RACT_SAME_STUDY_ERROR_MESSAGE: 'Current template can\'t be assigned to same study.',
  RACT_ASSIGN_STUDY_ID_ERROR_MESSAGE: 'Study ID can\'t be empty..',
  RACT_START_DATE: 'start-date',
  RACT_ADD_NEW_STUDY_NAME_INPUT_ID: 'study-name-input',
  RACT_ADD_NEW_PROTOCOL_ID_INPUT: 'protocol-id-input',
  RACT_ADD_NEW_SPONSOR_INPUT: 'sponsor-name-input',
  RACT_ADD_NEW_PROGRAM_INPUT: 'program-input',
  RACT_ADD_NEW_THERAPEUTIC_AREA_INPUT: 'therapeutic-area-input',
  RACT_ADD_NEW_INDICATION_INPUT: 'indication-input',
  RACT_ASSIGN_RACT_TYPE_SELECTED_STUDY: 'selected-study',
  RACT_ASSIGN_RACT_TYPE_SELECTED_TEMPLATE: 'selected-template',
  RACT_ASSIGN_TEMPLATE_TOAST_ERROR: 'Template already assigned to study',
  RACT_ASSIGN_TEMPLATE_SUCCESSFULLY: 'Template assigned successfully',
  RACT_RISK_CATEGORY_RANGE_1_5: '1-5',
  RACT_RISK_CATEGORY_RANGE_1_10: '1-10',
  RACT_END_DATE: 'end-date',
  RACT_STATUS_DRAFT: 'draft',
  RACT_STATUS_PUBLISHED: 'published',
  RACT_STATUS_PUBLISHED_STATUS: 'Published',
  RACT_OOB: 'LSAC RACT Template - V1',
  RACT_OOB_1: 'LSAC RACT Template - V2',
  RACT_OOB_TEMPLATE: ' (OOB Template)',
  RACT_EXPIRE: 'expire',
  RACT_SIGNOFF_DONE: 'signed',
  RACT_REJECTED: 'rejected',
  RACT_OK: 'OK',
  RACT_CUSTOM_TEMPLATE: ' (Custom Template)',
  RACT_CONSOLE_DATA: 'ractConsoleData',
  RACT_STUDY_FILTER_ARRAY: 'ractStudyFilterArray',
  RACT_TOTAL_CATEGORY_COUNT: 'Total Category Count',
  RACT_ENABLED_CATEGORY_COUNT: 'Enabled Category Count',
  RACT_TOTAL_SUB_CATEGORY_COUNT: 'Total SubCategory Count',
  RACT_ENABLED_SUB_CATEGORY_COUNT: 'Enabled SubCategory Count',
  RACT_MITIGATION_ACTION_COUNT: 'Mitigation Action Count',
  RACT_STUDY_PROGRAM: 'Study Program',
  RACT_STUDY_THERAPEUTIC_AREA: 'Study Therapeutic Area',
  RACT_STUDY_MEDICAL_INDICATION: 'Study Medical Indication',
  RACT_STUDY_PHASE: 'Study Phase',
  RACT_STUDY_STATUS: 'Study Status',
  RACT_STUDY_CRO_NAMES: 'Study CRO Names',
  RACT_STUDY_START_DATE: 'Study Start Date',
  RACT_STUDY_PLANNED_END_DATE: 'Study Planned End Date',
  RACT_STUDY_CURRENT_MILESTONE: 'Study Current Milestone',
  RACT_STUDY_REGIONS: 'Study Regions',
  RACT_STUDY_SPONSORS: 'Study Sponsor',
  RACT_STUDY_PLANNED_ENROLLMENT_COUNT: 'Study Planned Enrollment Count',
  RACT_STUDY_ACTUAL_ENROLLMENT_COUNT: 'Study Actual Enrollment Count',
  RACT_STUDY_CURRENT_SITE_ACTIVATION_COUNT: 'Study Current Site Activation Count',
  RACT_STUDY_TARGET_SITE_ENROLLMENT_COUNT: 'Study Target Site Activation Count',
  RACT_STUDY_DESCRIPTION: 'Study Description',
  RACT_TEMPLATE_CONFIGURATION: 'RACT Template Configuration',
  RACT_ASSESSMENT_EXPORT_CSV_FILENAME: 'Ract-Assessment-Export',
  RACT_CONSOLE_EXPORT_CSV_FILENAME: 'Ract-Console-Export',
  RACT_STUDIES: 'ractStudies',
  RACT_MASTER_STUDIES: 'masterStudies',
  RACT_CUSTOM: 'custom',
  IS_RACT_ASSIGNED: 'isRactAssigned',
  IS_RACT_CONSOLE_DATA_LOADED: 'isRactConsoleDataLoaded',
  RECORDING: 'Recording',
  REGION: 'Region',
  RELATIONSHIP_TO_TASK: 'Relationship to task',
  REMOVE: 'Remove',
  REMOVE_ACCESS: 'Remove access',
  REMOVE_ALL_ACCESS_WARNING: "One or more of the updates you've made include removing all access for user(s) or team(s). This means they will no longer be able to access the analytics, dashboard or folder.",
  REMOVE_ASSIGNEE: 'Remove assignee',
  REMOVING_ASSIGNEES: 'Removing assignees',
  RENAME: 'Rename',
  RENAME_FOLDER: 'Rename Folder',
  RENDER: 'Render',
  REPORT: 'Analytics',
  REPORT_CONTAINS_ERRORS: 'Analytics contains errors and can not be displayed.',
  REPORT_DATA_FAILED_TO_LOAD: function (analyticTitle) {
    return `Analytics data failed to load for analytics ${analyticTitle}.`;
  },
  REPORT_DETAIL_OPENER: 'Underlying Data, Related Dashboards/Analytics & Export Options',
  REPORT_DETAIL_RELATED_DASHBOARDS: 'Related Dashboards',
  REPORT_DETAIL_RELATED_REPORTS: 'Related Analytics',
  REPORT_FAILED_TO_EXECUTE_QUERY: 'Failed to execute query.',
  REPORT_FAILED_TO_PARSE_QUERY: 'Failed to parse CQL query.',
  REPORT_NAME: 'Analytics name',
  REPORT_NAME_IS_REQUIRED: 'Analytics name is required.',
  REPORT_SCHEMA: 'Analytics Schema',
  REPORT_TYPE: 'Analytics Type',
  REPORT_TYPE_INVALID: 'The currently selected analytics type is invalid.',
  REPORTS: 'Analytics',
  REPORTS_COMMON_SCHEMA: 'Analytics Common Schema',
  REPORTS_DASHBOARDS_FOLDERS_MONITORS: 'Analytics, dashboards, folders and monitors',
  REPORTS_TO_DELETE_HAVE_DASHBOARDS: {
    singular: 'The analytics you are deleting are used in the following dashboards:',
    plural: 'The analytics you are deleting are used in the following dashboards:',
  },
  REQUIRED: 'required',
  REQUIRED_FIELD_ERROR_MESSAGE: 'This is a required field',
  RESENT_INVITATION_EMAIL_TO_NEW_USER: function (email) {
    return `An invitation to join this account has been re-sent${(email ? ` to '${email}'` : '')}. The status will remain as 'pending' until the invitation is accepted.`;
  },
  RESET: 'Reset',
  RESET_ALL: 'Reset all',
  RESET_PASSWORD: 'Reset password',
  RETURN: 'Return',
  RETURN_TO_EDIT: 'Return to Edit',
  REVIEW_ROLE_STATUS_ACTIVE: 'Active',
  REVIEW_ROLE_STATUS_DISABLED: 'Disabled',
  REVIEWER: 'Reviewer',
  REVIEWED_DATE: 'Reviewed Date',
  REVIEWED_ROLE: 'Review Role(s)',
  RISK_SCORE: 'Risk Score',
  RACT_TEMPLATE: 'Ract Template',
  ROLE: 'Role',
  ROLES: 'Roles',
  ROOT_DIRECTORY: 'Root Directory',
  RUN: 'Run',
  SAMPLE_DATA_TEXT: function (numColumns) {
    return `Sample Data from ${numColumns} columns.`;
  },
  SAVE: 'Save',
  SAVE_AND_DEPLOY: 'Save & Deploy',
  SAVE_MY_PASSWORD: 'Save my password',
  SCALAR: 'Scalar',
  SCHEDULE: 'Schedule',
  SCHEDULE_FORMAT_ERROR_MESSAGE: 'Schedule must be specified in ISO8601 repeating interval format.',
  SCHEMA_IS_REQUIRED: 'Schema is required',
  SCREENSHOT:'Screenshot',
  SCORE: 'Score',
  SCORE_FORMULA: 'Score formula',
  SCORECARD: 'Scorecard',
  SCORECARD_CATEGORY: "Scorecard Category",
  SCORE_DISPLAY_SETTINGS: 'Score Display Settings',
  SEARCH_FOR_A_TEMPLATE: 'Search for a template',
  SEARCH_STUDY: 'Search for a study',
  SELECT: 'Select',
  SELECT_A_DESTINATION: 'Select a destination',
  SELECT_A_LINKED_REPORT_OR_DASHBOARD: 'Select a linked analytics or dashboard',
  SELECT_A_SCHEMA: 'Select a Schema',
  SELECT_A_TYPE: 'Select a type',
  SELECT_AN_ACCOUNT: 'Select an Account',
  SELECT_ANALYTICS_DASHBOARDS_TO_ASSOCIATE: 'Select Analytics/Dashboards to Associate',
  SELECT_ASSIGNEE: 'Select assignee',
  SELECT_DASHBOARDS_REPORTS: 'Select dashboards/analytics',
  SELECT_ENTIRE_TABLE: 'Select entire table',
  SELECT_FILTERS_TO_BEGIN_REVIEW: 'Select filters to begin review',
  SELECT_FILTERS_TO_PROCEED: 'Select filters to proceed',
  SELECT_OBSERVERS: 'Select observers',
  SELECT_RELATED_DASHBOARD_REPORTS_FOR: function (templateName) {
    return `Select related dashboard/analytics for "${templateName}"`;
  },
  SELECT_REPORTS: 'Select analytics',
  SELECT_ROLES: 'Select roles',
  SELECT_TABULAR_REPORTS: 'Select tabular analytics',
  SELECT_METRIC_FROM_CATEGORY: 'Please select one metric from the category.',
  SELECTED_ITEMS: 'selected items',
  SELF_SUBTEXT: '(self)',
  SENT_INVITATION_EMAIL_TO_NEW_USER: function (email) {
    return `An invitation to join this account has been sent${(email ? ` to '${email}'` : '')}. The status will remain as 'pending' until the invitation is accepted.`;
  },
  SENT_PASSWORD_RESET_EMAIL_TO_USER: function (email) {
    return `A link to reset password has been sent${(email ? ` to '${email}'` : '')}.`;
  },
  SESSION: 'Session',
  SESSION_FILTER: 'Session filter',
  SHARE: 'Share',
  SHARE_ITEMS: 'Share items',
  SHARE_KPIS: 'Share KPIs',
  SHARE_KPIS_CONFIGURATION_WARNING: 'Current sharing configuration excludes the following report dependencies:',
  SHARING_ADD_MODAL_LINK_TO_EDIT: 'Edit & View Sharing options',
  SHARING_ADD_USERS_OR_TEAMS: 'Add users and/or teams to share this item',
  SHARING_EDIT_MODAL_LINK_TO_ADD: 'Share with More Users',
  SHARING_EDIT_MODAL_TEXT_GROUPS: function (fileType) {
    return `Teams that have access to this ${convertReportToAnalytics(fileType).toLowerCase()}:`;
  },
  SHARING_EDIT_MODAL_TEXT_USERS: function (fileType) {
    return `Users who have access to this ${convertReportToAnalytics(fileType).toLowerCase()}:`;
  },
  SHARING_ENTITY_TYPE_DISPLAY_NAME: function (entityType) {
    switch (entityType) {
      case ExposureAppConstants.RBAC_ENTITY_TYPE_GROUP_ENTITY:
        return 'Teams';
      case ExposureAppConstants.RBAC_ENTITY_TYPE_USER_ENTITY:
        return 'Users';
    }
  },
  SHARING_NONE_OF_YOUR_CHANGES: 'If you close this dialog, none of your changes will be applied. Are you sure you want to discard your changes?',
  SHARING_TEAM_AND_USER_DROPDOWN_PLACEHOLDER: 'Select from list one at a time',
  SHARING_UNSUCCESSFUL: 'Sharing unsuccessful',
  SHARING_UNSUCCESSFUL_DETAILS: 'The item could not be shared.',
  SHARING_USERS_COULD_NOT_BE_ADDED_OR_MODIFIED: function (sharingRequestType) {
    var baseText = 'The following user(s) could not be ';
    switch (sharingRequestType) {
      case ExposureSharingConstants.SHARE_REQUEST_TYPE_ADD:
        return baseText + 'added';
      case ExposureSharingConstants.SHARE_REQUEST_TYPE_MODIFY:
        return baseText + 'modified';
    }
  },
  SHOW:'Show',
  SHOW_ONLY_OPEN_TASKS: 'Show only open tasks',
  SHOW_ONLY_THRESHOLD_BREACHES: 'Show only threshold breaches',
  SIGN_IN: 'Sign in',
  SIMPLE: 'Simple',
  SIMULATED_THRESHOLD: 'Simulated threshold',
  SITE: 'Site',
  SITE_CRA_NAME: 'Site CRA Name',
  SITE_NAME: 'Site Name',
  SITE_ID: 'Site ID',
  SITE_SCORE: 'Site Score',
  SITE_STATUS: 'Site Status',
  PI_NAME: 'PI Name',
  PI_EMAIL: 'PI Email',
  SITE_FPFV: 'FPFV',
  SITE_SCORECARD_FILTERS_NO_SELECT: 'Please select a study to view the site scorecard.',
  SITES: 'Sites',
  SLIDER: 'Slider',
  SNAPSHOT:'Screenshot',
  SNAPSHOT_NO:'No',
  SNAPSHOT_YES:'Yes',
  SNAPSHOT_REPLACE:'Do you want to replace previous snapshot?',
  SNAPSHOT_MANUALLY:'Manually ',
  SNAPSHOT_AUTOMATICALLY:'Automatically ',
  SNAPSHOT_CAPTURED_AT:'captured at ',
  SNAPSHOT_CAPTURE:'Capture Snapshot',
  SNAPSHOT_REMOVE:'Remove Snapshot',
  SCREENSHOT_CAPTURE:'Capture Screenshot',
  SCREENSHOT_REMOVE:'Remove Screenshot',
  SOME_PROPERTIES_ARE_NOT_DISPLAYED_FOR_DRILLDOWN: 'Some properties are not displayed in the drilldown filter context.',
  SORT: 'Sort',
  SPONSOR: 'Sponsor',
  STANDARD_DEVIATION: 'Standard Deviation',
  STATE: 'State',
  STATIC: 'Static',
  STATIC_FILTER: function (id) {
    return `Static filter ${id}`;
  },
  STATIC_FILTERS_INSTRUCTIONS: 'filters that are fixed / analytics viewers cannot interact with.',
  STATUS: 'Status',
  STUDY: 'Study',
  STUDY_ID: 'Study ID',
  STUDY_IS_NOT_ASSIGNED_TO_ANY_METRIC_GROUP: function (study) {
    return `Study ${study} is not assigned to any metric group`;
  },
  STUDY_NAME: 'Study Name',
  STUDY_PHASE: 'Phase',
  STUDY_SCORE: 'Study Score',
  STUDIES: 'Studies',
  STUDIES_IN_THIS_DATA_ACCESS_GROUP: function (count, isAllAccessProfile) {
    if (isAllAccessProfile) {
      return 'All studies in this data access group';
    } else {
      const studyString = count === 1 ? 'study' : 'studies';
      return `${count} ${studyString} in this data access group.`;
    }
  },
  SUBJECTS: 'Subjects',
  SUCCESS: 'Success',
  SUCCESS_A_NEW_DATA_ACCESS_GROUP_HAS_BEEN_ADDED: 'Success: A new data access group has been added',
  SUCCESS_A_NEW_DATA_REVIEW_ROLE_HAS_BEEN_ADDED: 'Success: A new data review role has been added',
  SUCCESS_A_NEW_TEAM_HAS_BEEN_ADDED: 'Success: A new team has been added',
  SUCCESSFULLY_CREATED: 'successfully created',
  SUFFIX: 'Suffix',
  SUM: 'Sum',
  SUMMARY: 'Summary',
  SWITCH_ACCOUNT: 'Switch account',
  TABLE: 'Table',
  TABLE_PREVIEWS_HERE: 'Table previews here',
  TABULAR_ANALYTICS_CREATED_HERE_ONLY_FOR_DATA_REVIEW_SETS:
    'Tabular Analytics created here should only be used in Data Review Sets.',
  TABULAR_REPORT: 'Tabular Analytics',
  TABULAR_VIEW: 'Tabular View',
  TASK:'Task',
  TASK_404_ERROR: 'This task does not exist, or you do not have access to it.',
  TASK_ASSIGNEES: 'Task assignees',
  TASK_CONFIGURATION: 'Task Configuration',
  TASK_MANAGEMENT_ACTIONS: 'Actions',
  TASK_MANAGEMENT_FIELD_NAME: 'Field Name',
  TASK_MANAGEMENT_FIELD_DESC: 'Field Description',
  TASK_MANAGEMENT_FIELD_TYPE: 'Field Type',
  TASK_ASSOCIATED_ANALYTICS_AND_DASHBOARD: 'Associated Analytics And Dashboard',
  TASK_LOV: 'LOV',
  TASK_MANAGEMENT_IS_MANDATORY: 'Is Mandatory',
  TASK_FILTER_DEPENDANCY: 'Filter Dependancy',
  TASK_NO_ASSOCIATION: 'This task is not associated with any dashboard, analytics, or data. Therefore, no visualization is displayed.',
  TASK_STATE: 'Task state',
  TASK_TYPE: 'Task type',
  TASK_TYPE_CANNOT_BE_EMPTY: 'Task type cannot be empty.',
  TASK_URGENCY: 'Task urgency',
  TASK_URGENCY_TOOLTIP_MESSAGE: 'When urgency is turned on, all future tasks generated by this data monitor will be marked as urgent.',
  TASK_RELATION_AUTHOR: 'AUTHOR',
  TASK_RELATION_ASSIGNEE: 'ASSIGNEE',
  TASK_RELATION_OBSERVER: 'OBSERVER',
  TASK_RELATION_NONE: 'NONE',
  TASKS: 'Tasks',
  TASK_RELATIONSHIP:'Task Relationship',
  TASK_LIST_SORT:'Sort by',
  TASK_LIST_SORT_PRIORITY:'Priority',
  TASK_LIST_SORT_MODIFIEDON:'Modified on',
  TEAM: 'Team',
  TEAM_NAME: 'Team Name',
  TEAM_NAME_IS_ALREADY_IN_USE: 'Team name is already in use.',
  TEAM_NAME_IS_REQUIRED: 'Team name is required.',
  TEAMS: 'Teams',
  TASK_DETAILS: 'Task Details',
  NO_TEAMS_CONFIGURED_FOR_THIS_ACCOUNT: 'No teams configured for this account',
  TEMPLATE_PARAMETERS: 'Template Parameters',
  TEMPLATE_QUERYPLAN: 'Template Query Plan',
  TEMPLATE_TYPE: 'Template Type',
  PDF_EXPORT_OPTIONS: 'Export to PDF Configurations',
  PAGE_SIZE: 'Page Size',
  TEMPLATES: 'Templates',
  TEMPLATES_DELETED: {
    singular: 'template has been successfully deleted!',
    plural: 'templates have been successfully deleted!',
  },
  THE_FOLLOWING_ACTIONS_ARE_IRREVERSIBLE: 'The following actions are irreversible:',
  THERAPEUTIC_AREA: 'Therapeutic Area',
  THERE_ARE_TWO_TYPES_OF_FILTERS: 'There are two types of filters you can create:',
  THERE_IS_NO_ASSOCIATED_REPORT_OR_DASHBOARD: 'There are no associated analytics or dashboards',
  THERE_IS_NO_SUMMARY: 'There is no summary.',
  THERE_WAS_AN_ERROR_AND_ONLY_A_PORTION_OF_THE_VIZ_COULD_BE_RENDERED: 'There was an error, and only a portion of the visualization could be rendered.',
  THERE_ARE_NO_ATTRIBUTES: function (type) {
    return `No ${type} Attributes Configured.`
  },
  THIS_ACTION_COULD_NOT_BE_COMPLETED: 'This action could not be completed',
  THRESHOLD: 'Threshold',
  THRESHOLD_CANNOT_BE_EMPTY: 'Threshold cannot be empty.',
  THRESHOLD_SCALAR: 'Threshold scalar',
  THRESHOLD_TYPE: 'Threshold type',
  TITLE: 'Title',
  TITLE_CANNOT_BE_EMPTY: 'Title cannot be empty.',
  TITLE_REQUIRED: 'Title (required)',
  TITLES_AND_LABELS: 'Titles and labels',
  INFOGRAPHIC_LABELS: 'Infographics ',
  DEFAULT_SUBJECT_INFORMATION: 'Default Subject information',
  TO: 'to',
  TO_CAPITALIZED: 'To',
  TO_CREATE_TABULAR_ANALYTICS_FOR_OTHER_PURPOSES:
    'To create Tabular Analytics for other purposes, please use KPI Studio.',
  TO_DATE: 'To Date',
  TRY_REFRESHING_YOUR_BROWSER: 'There was a problem loading your home page. Please try refreshing your browser.',
  UNEXPECTED_SERVER_ERROR: 'Unexpected server error',
  DUPLICATE_DISPOSITION_NAMES: 'Disposition not updated - All Disposition Labels must be unique',
  DISPOSITION_FIRSTEVENT_NOTACTIVESTATUS_UPDATE:'Cannot Save Configuration without setting First Event with an Active State',
  FIRST_EVENT_MUST_BE_SELECTED: 'One configured event must be specified as the first event',
  UNSAVED_WORK: 'You have unsaved work. If you navigate away, you will lose your changes.',
  UPDATE: 'Update',
  UPDATED_AT:'updatedAt',
  UPDATE_DATA_ACCESS_GROUPS_FOR_USERS_FAILED: 'Failed to update data access groups for users.',
  UPDATE_DATA_REVIEW_ROLES_FOR_USERS_FAILED: 'Failed to update data review roles for users.',
  UPDATE_FILE_UNSUCCESSFUL: function (fileType) {
    return `Status update: Update ${convertReportToAnalytics(fileType)} was unsuccessful.`;
  },
  UPDATE_FILES_UNSUCCESSFUL: 'Status update: Update files was unsuccessful.',
  UPDATE_DISPOSITIONS_SUCCESSFUL: 'Status update: Update disposition configuration was successful.',
  UPDATE_OVERSIGHT_SCORECARD_CONFIG_SUCCESSFUL: 'Oversight scorecard metric configuration updated successfully',
  OS_GROUP_ADDED_STUDIES_SUCCESS: function (name, addedStudyNames) {
    return `Configuration ${name} has been associated with Study ${addedStudyNames}`;
  },
  OS_GROUP_REMOVED_STUDIES_SUCCESS: function (name, removedStudyNames) {
    return `Configuration ${name} has been disassociated with Study ${removedStudyNames}`;
  },
  UPDATE_USER_PERMISSIONS_FAILED: 'Failed to update permissions.',
  UPDATED: 'Updated',
  UPDATED_USER_DATA_ACCESS_GROUP: 'Updated user data access group',
  UPDATED_USER_DATA_REVIEW_ROLE: 'Updated user data review role',
  UPDATED_USER_DETAILS: 'Updated user details.',
  UPDATED_USER_ROLE: function (name, oldRole, newRole) {
    return `The role of ${name} has been updated from ${oldRole} to ${newRole}.`;
  },
  UPLOAD: 'Upload',
  UPLOAD_DATA_REVIEW_FILE_DATA_FAILED: 'Failed to upload data review file data.',
  URGENCY: 'Urgency',
  URGENCY_ICON: "!",
  URGENT: 'Urgent',
  URGENT_ONLY: 'Urgent only',
  USE_KPI_STUDIO_REPORTS: 'Use KPI Studio Reports',
  USE_SSO: 'Use SSO',
  USER_DETAILS: 'User Details',
  USER_MANAGEMENT: 'User Management',
  USER_NAME: 'User Name',
  USER_PERMISSIONS: 'User Permissions',
  USER_PROFILE: 'User Profile',
  USER_PROFILE_FIELDS_ERROR: 'User First name and Last name fields must be filled',
  USER_UPDATED_SUCCESFULLY: 'User was updated succesfully',
  USER_UPDATED_UNSUCCESFULLY: 'User update failed',
  USER_STATUS_ACTIVE: 'Active',
  USER_STATUS_INACTIVE: 'Inactive',
  USER_STATUS_LINK_EXPIRED: 'Link Expired',
  USER_STATUS_PENDING: 'Pending',
  USER_TYPE: 'User Type',
  USER_TYPES: 'User Types',
  USERS: 'Users',
  USERS_CAN_PERFORM_THE_FOLLOWING_ACTIONS: 'Users can perform the following actions for those documents and tasks they have been granted proper access to.',
  USERS_IN_THIS_TEAM: function (count) {
    return `${count} users in this team.`;
  },
  VALIDATION_VALUE_IS_REQUIRED: 'Value is required',
  VALIDATION_MIN_VALUE_LENGTH: 'Field length is too short',
  VALIDATION_MAX_VALUE_LENGTH: 'Field length is too long',
  VALIDATION_MIN_NUMBER_SELECTED_ITEMS: 'Number of selected items is too small',
  VALIDATION_MAX_NUMBER_SELECTED_ITEMS: 'Number of selected items is too big',
  VALIDATION_FLOAT: 'Field should be number',
  VALIDATION_INTEGER: 'Field should be integer number',
  VALIDATION_MIN_VALUE: (testValue) => `Field value should be more or equal than ${testValue}`,
  VALIDATION_MAX_VALUE: (testValue) => `Field value should be less or equal than ${testValue}`,
  VALIDATION_NOT_EQUAL_VALUE: (testValue) => `Field value should not be equal to ${testValue}`,
  VERIFYING: 'Validating entry...',
  VERSION: 'Version',
  VIEW: 'View',
  VIEW_COMMENT: 'View / Comment',
  VIEW_CURRENT: 'View current',
  VIEW_LESS: 'View less',
  VIEW_MORE: 'View more',
  VIEW_SIMULATED: 'View simulated',
  VIEW_EDIT_SHARE_MOVE: 'View / Edit / Share / Move',
  VIEW_TASK: 'View Task',
  VIEW_USER_TYPE_DEFINITIONS: 'View user type definitions',
  VIZ_SPECS_DEFINITION: 'Viz Specs Definition',
  VIZ_SPECS_DEFINITION_TIP: 'To access processed data, use data. Viz-spec must be an array.',
  WEIGHT: 'Weight',
  WEIGHTS: 'Weights',
  YES_ERASE_SETTINGS: 'Yes, erase settings',
  YOU_ARE_NOT_OWNER_TO_DELETE: {
    singular: 'The following item you have selected cannot be deleted because you are not the owner:',
    plural: 'The following items you have selected cannot be deleted because you are not the owner:',
  },
  YOU_CANNOT_SHARE: function (fileTypeName) {
    return `Currently you are not enabled to share this ${fileTypeName.toLowerCase()}`;
  },
  YOU_CANNOT_SHARE_ITEMS: 'Currently you are not enabled to share these items',
  YOU_CANNOT_MOVE_BUILD_IN_KPI: 'The following item(s) cannot be moved as they are built-in report(s):',
  YOU_CANNOT_DELETE_BUILD_IN_KPI: "The following item(s) cannot be deleted as they are built-in report(s):",
  YOU_DO_NOT_HAVE_SUFFICIENT_PERMISSIONS: 'You do not have sufficient permissions to perform the operation.  Please contact the account administrator if you need additional help.',
  YOU_HAVE_ADDED_A_NEW_SESSION_FILTER: 'You have added a new session filter.',
  YOU_HAVE_ADDED_A_TASK: 'Task has been created successfully.',
  YOU_HAVE_CLEARED_ALL_DRILLDOWN_AND_OR_TASK_FILTERS: 'You have cleared all drilldown and/or task filters.',
  YOU_HAVE_DELETED_FILTER: function (type, id) {
    return `You have deleted '${type} Filter ${id}'`;
  },
  YOU_HAVE_EXCEED_THE_MAXIMUM_NUMBER_OF_LOGIN_ATTEMPTS: 'You have exceeded the maximum number of login attempts. Please use the Reset password link below to reset your password.',
  YOU_HAVE_NO_ITEMS_AT_THIS_TIME: (itemType) => `You have no ${(itemType || 'ITEMS').toLowerCase()} at this time.`,
  YOU_HAVE_SUCCESSFULLY_ADDED_A_METRIC_GROUP: 'You have successfully added a metric group.',
  YOU_HAVE_SUCCESSFULLY_ADDED_A_TEAM: 'You have successfully added a team.',
  YOU_HAVE_SUCCESSFULLY_ADDED_ASSIGNEES: 'You have successfully added assignees.',
  YOU_HAVE_SUCCESSFULLY_UPDATED_DATA_ACCESS_GROUP_ASSIGNMENTS: 'You have successfully updated data access group assignments',
  YOU_HAVE_SUCCESSFULLY_UPDATED_DATA_REVIEW_ROLE_ASSIGNMENTS: 'You have successfully updated data review role assignments',
  YOU_HAVE_SUCCESSFULLY_UPDATED_THE_ASSIGNEES_LIST: 'You have successfully updated the assignees list.',
  YOU_HAVE_SUCCESSFULLY_UPDATED_THE_DATA_ACCESS_GROUP: ' You have successfully updated the data access group.',
  YOU_HAVE_SUCCESSFULLY_UPDATED_THE_DATA_REVIEW_ROLE: 'You have successfully updated the data review role.',
  YOU_HAVE_SUCCESSFULLY_UPDATED_THE_METRIC_GROUP: 'You have successfully updated the metric group.',
  YOU_HAVE_SUCCESSFULLY_UPDATED_THE_TEAM: 'You have successfully updated the team.',
  YOU_HAVE_SUCCESSFULLY_UPDATED_USER_PERMISSIONS: 'You have successfully updated user permissions.',
  YOU_HAVE_SUCCESSFULLY_UPLOAD_DATA_REVIEW_DATA: 'You have successfully uploaded review file data',
  YOU_HAVE_SUCCESSFULLY_DELETED_A_SESSION_FILTER: 'You have successfully deleted a session filter.',
  YOU_HAVE_SUCCESSFULLY_DELETED_THE_METRIC_GROUP: 'You have successfully deleted the metric group',
  YOU_HAVE_UPDATED_A_TASK: 'You have updated a task',
  YOUR_CREDENTIALS_ARE_INCORRECT_PLEASE_TRY_AGAIN: 'Your credentials are incorrect. Please try again.',
  YOUR_HOMEPAGE_HAS_NOT_BEEN_SAVED: 'Your Homepage has not been saved',
  YOUR_PASSWORD_HAS_EXPIRED: 'Your password has expired. For security purposes, it must be changed every 90 days using the Reset password link below.',
  YOUR_SESSION_IS_ABOUT_TO_END: 'As a security precaution, your session is about to end due to inactivity. If you are still working, please click "OK" to continue your session.',
  YOUR_SESSION_WILL_END: 'Your session will end in 1 minute due to inactivity',
  YOUR_HOME_PAGE_NOT_CONFIGURED: 'Your home page has not been configured.',
  YOUR_PROFILE: 'Your Profile',
  BOT_FILTER_FAILED: 'Cannot apply filters',
  BOT_RUN_FAILED: 'Could not connect to server',
  BOT_DB_CONNECT_FALIED: 'Could not connect to database server',
  BOT_AUDIT_FAILED: 'Failed to audit data',
  RACT_TEMPLATE_CREATED: 'New ract template created successfully',
  RACT_TEMPLATE_UPDATED: 'Ract template updated successfully',
  RACT_TEMPLATE_NAME_ERROR: 'Please add template name',
  RISK_SCALE_UPDATED: 'Risk scale updated successfully',
  RISK_SCALE_ONE_TO_FIVE: '1-5',
  RISK_SCALE_ONE_TO_TEN: '1-10',
  RISK_CATEGORY_DUPLICATE: 'Risk category with same name already exists',
  RISK_CATEGORY_UPDATED: 'Risk category updated successfully',
  RISK_CATEGORIES_DISABLED: 'All risk categories are disabled',
  RISK_SUBCATEGORY_EMPTY: 'Add at least one risk subcategory to save custom risk category',
  RISK_SUBCATEGORY_DUPLICATE: 'Risk subcategory with same name already exists',
  RACT_ASSESSMENT_VALIDATION_MSG: 'Following categories are remaining to fill. Please fill and save then Sign-off :-',
  RACT_ASSESSMENT_FUNCTIONAL_PLAN_SUCCESS: 'Functional Plan updated successfully',
  RACT_ASSESSMENT_MITIGATION_ACTION_SUCCESS: 'Mitigation Action updated successfully',
  RACT_ASSESSMENT_REVIEW_APPROVE_NAME: 'Approve',
  RACT_ASSESSMENT_REVIEW_REJECT_NAME: 'Reject',
  RACT_ASSESSMENT_TOTAL_RISK_SUBCATEGORY_SCORE_ERROR_MSG: 'Total Risk Score Should Not Be Zero.',
  RACT_ASSESSMENT_FUNCTIONAL_CATEGORY_ERROR_MSG: 'Functional Plan Should Not Be Empty.',
  RACT_ASSESSMENT_MITIGATION_ACTION_ERROR_MSG: 'Mitigation Action Should Not Be Empty.',
  RACT_ASSESSMENT_MONITORS_ERROR_MSG: 'Monitor Should Not Be Empty.',
  RACT_ASSESSMENT_QUESTION_EDIT_OPTION_NAME: 'question',
  RACT_ASSESSMENT_CONSIDERATION_EDIT_OPTION_NAME: 'consideration',
  RACT_ASSESSMENT_UNABLE_TO_SIGN_OFF_TEXT: 'Unable to Sign-off',
  RACT_ASSESSMENT_UNABLE_TO_SAVE_TEXT: 'Unable to Save',
  RACT_ASSESSMENT_VALIDATION_MSG_TEXT: 'Please fill in all mandatory fields for the selected risk subcategory',
  RACT_ASSESSMENT_FUNCTIONAL_PLAN_ADD_LABEL: 'Add Functional Plan',
  RACT_ASSESSMENT_FUNCTIONAL_PLAN_ADD_PLACEHOLDER: 'Enter a functional plan...',
  RACT_ASSESSMENT_MITIGATION_ACTION_ADD_LABEL: 'Add Mitigation Action',
  RACT_ASSESSMENT_MITIGATION_ACTION_ADD_PLACEHOLDER: 'Enter a Mitigation Action...',
  RACT_ASSESSMENT_REVIEW_REJECTION_HEADER_TEXT: 'RACT Rejection Comment',
  RACT_ASSESSMENT_REVIEW_REJECTION_COMMENT_PLACEHOLDER: 'Enter a Rejection Comment...',
  RACT_ASSESSMENT_REVIEW_APPROVE_HEADER_TEXT: 'RACT Approve Comment',
  RACT_ASSESSMENT_REVIEW_APPROVE_COMMENT_PLACEHOLDER: 'Enter a Approve Comment...',
  RACT_ASSESSMENT_REVIEW_CANCEL_TEXT: 'Cancel',
  RACT_ASSESSMENT_REVIEW_SUBMIT_TEXT: 'Submit',
  RACT_ASSESSMENT_HEADER: 'Risk Category',
  RACT_ASSESSMENT_SAVE_BUTTON_TEXT: 'Save',
  RACT_ASSESSMENT_SAVE_AND_SIGNOFF_BUTTON_TEXT: 'Next >',
  RACT_PREVIEW: 'No Preview Available',
  RACT_CATEGORY_DISABLED: 'This category is disabled',
  RACT_SUBCATEGORY_DISABLED: 'All subcategories are disabled',
  RACT_API_ERROR: 'HTTP error! status:',
  RACT_RISK_CATEGORY_API_ERROR: 'Failed to load riskcategories',
  RACT_SUBCATEGORY_QUESTION_ERROR: 'Please add questions for all subcategories',
  RACT_ASSESSMENT_SUBCATEGORY_RISK_QUESTION_ERROR: 'Risk Question Should Not Be Empty.',
  RACT_MITIGATION_ADD_VALIDATION_MSG: 'Mitigation Action With Same Name Already Exist',
  RACT_FUNCTIONAL_PLAN_VALIDATION_MSG: 'Functional Plan With Same Name Already Exist',
  ASSIGN_USER_ERROR: 'Please select user',
  USER_ASSIGNED: 'User assigned successfully',
  RACT_ID_NOT_PRESENT: 'Ract id not present, please go to assessment page',
  ASSESSMENT_REVIEW_SUCCESS_MSG: 'Ract Template has been successfully Signed off.',
  RACT_ASSESSMENT_CATEGORY_SAVE_SUCCESS: 'Category Saved Successfully.',
  ASSESSMENT_SAVE_AND_SIGNOFF_SUCCESS_MSG: 'RACT has been created successfully',
  ASSESSMENT_REVIEW_REASSIGN_NAME: 'reAssign',
  ASSESSMENT_REVIEW_NOT_REASSIGN_NAME: 'notReAssign',
  RACT_VALID_CATEGORY: 'Add valid category name',
  RACT_VALID_SUBCATEGORY: 'Add valid subcategory',
  RACT_ASSIGN_SIGNING_AUTHORITY: 'Assign RACT Review Task to Users',
  RACT_TEMPLATE_FINAL_STATUS: 'Final',
  RACT_TEMPLATE_FINAL: 'final',
  RACT_TEMPLATE_DRAFT_STATUS: 'Draft',
  OOB_RACT_TEMPLATE_ID: '11111111-1111-1111-1111-111111111111',
  OOB1_RACT_TEMPLATE_ID: '11111111-1111-1111-1111-111111111112',
  RACT_CREATE_TEMPLATE: 'Create New RACT Template',
  RACT_VIEW_TEMPLATE: 'View RACT Template',
  RACT_UPDATE_TEMPLATE: 'Update RACT Template',
  RACT_TEMPLATE_DELETED: 'Ract template deleted successfully',
  RACT_TEMPLATES_DELETE_MSG: (templateName, studyName) => {
    if (studyName) {
      return `The Template ${templateName} is assigned to study ${studyName}, Do you really want to delete this template?`
    } else {
      return `Do you really want to delete this ${templateName} template?`
    }
  },
  RACT_MONITOR_INACTIVE_STUDY_ERROR_MESSAGE: (StudyName) => {
    return `${StudyName}- This study mapping is not yet configured on the LSAC Application. You will not be able to review any performance metrics until the data for this study has been mapped.`
  },
  RACT_RELATED_KPI_INACTIVE_STUDY_ERROR_MESSAGE: (StudyName) => {
    return `${StudyName}- This study mapping is not yet configured on the LSAC Application. You will not be able to review any performance metrics until the data for this study has been mapped.`
  },
  RACT_ASSESSMENT_ALL_CATEGORY_DISABLED_MESSAGE: 'Atleast one category should be enabled !',
  RACT_ASSESSMENT_ALL_SUBCATEGORY_DISABLED_MESSAGE: 'Atleast one subcategory should be enabled OR disable the category !',
  RACT_REPORT_NOT_ACCESSIBLE_MESSAGE: `This report doesn't exist or you don't have access to it.`,
  ACTION_TAKEN_FILTER: 'Action Taken',
  TASK_STATUS_FILTER: 'Task Status',
  RACT_UNSAVE_CHANGES_MESSAGE_TEXT: `You have unsaved items on the console, on closing this page your changes will be lost, would you like to proceed without saving?`,
  RACT_UNSAVE_CHANGES_YES_BUTTON_TEXT: 'Yes',
  RACT_UNSAVE_CHANGES_NO_SAVE_CHANGES_BUTTON_TEXT: 'No- Save Changes',
  RACT_ASSESSMENT_TAB_CHANGE: 'tabChange',
  RACT_ASSESSMENT_PAGE_CLOSE: 'assessmentPageClose',
  RACT_ASSESSMENT_VERSION_TITLE: `RACT Assessment Versions`,
  RACT_ASSESSMENT_TITLE: `ASSESSMENT`,
  DOWNLOAD_DELAY_CONFIRMATION_MESSAGE: 'The csv file is being prepared for download in new tab. Meanwhile, you can use DaLIA for your next query. Thank you for your patience.',
  PDF_EXPORT_INITIATED: (dashboardName) => {
    return `The PDF file for ${dashboardName} will be downloaded shortly.`
  },
  TASK_MANAGEMENT_BLANK_RECORDS_MESSAGE: 'Some mandatory fields are blank. Please fillup or delete those fields and save.',
  TASK_MANAGEMENT_DUPLICATE_FIELD_NAME_MESSAGE: 'Duplicate field name. Please change field name or delete those fields and save',
  TASK_MANAGEMENT_EMPTY_ASSOCIATED_LIST: 'Please select atleast one associated dashboard or report to proceed.',
  TASK_MANAGEMENT_EMPTY_DATE_CONDITIONS: 'Please select atleast one date condition to proceed.',
  TASK_MANAGEMENT_DUPLICATE_LOVS: 'Duplicate LOVs. Please change or delete those fields and save',
  TASK_MANAGEMENT_RESET_DEPENDENCY_MESSAGE: 'Filter dependencies will get Reset with these changes.',
  TASK_MANAGEMENT_DELETE_ATTRIBUTE_MESSAGE: 'Are you sure you want delete this attribute?',
  TASK_MANAGEMENT_SAVE: 'Do you want to save?',
  TASK_MANAGEMENT_RESET_CONTINUE: 'Do you want to continue?',
  UPDATE_TASK_MANAGEMENT_SUCCESSFUL: 'Successfully updated task configuration.',
  ADD_CLINICAL_ATTRIBUTE: 'Add Clinical Attributes',
  VIEW_CLINICAL_ATTRIBUTE: 'View Clinical Attribute - ',
  MULTI_LEVEL_SORT: 'Multi Level Sort',
  COLUMN: 'Column',
  SELECT_COLUMN: 'Select Column',
  SELECT_ORDER: 'Select Order',
  ASCENDING: 'Ascending',
  DESCENDING: 'Descending',
  DESC:'desc',
  SORT_BY: 'Sort By',
  THEN_BY: 'Then By',
  COLLABORATION_CONTEXT:'COLLABORATION_CONTEXT',
  ADD_TASK:'ADD_TASK',
  ADD_COMMENT:'ADD_COMMENT',
  COMMENT_LIST:'COMMENT_LIST',
  TASK_LIST:'TASK_LIST',
  ASSIGN_ME: 'Assigned To Me',
  OBSERVE_ME: 'Observed By Me',
  OWN_ME: 'Owned By Me',
  CLINICAL_INSIGHTS: 'Clinical Insights',
  OPERATIONS_INSIGHTS: 'Operations Insights',
  KPI_STUDIO: 'KPI Studio',
  CDR: 'Clinical Data Review',
  COLUMN_NAME_STUDYNAME: 'studyname',
  COLUMN_NAME_STUDYID: 'studyid',
  COLUMN_NAME_SITENAME: 'sitename',
  COLUMN_NAME_SITEID: 'siteid',
  COLUMN_NAME_COUNTRY: 'sitecountry'
};

// Helper humanizer function.
function humanizer(millis) {
  if (millis === 24 * 60 * 60 * 1000) {
    // FIXME: We specify 24 hours here as a visual preference -- this value would result in "a day"
    // in the default case. `Moment.duration(millis).humanize()` also does weird rounding and is not
    // always exact, so this should be revisited if people start to use timeout values that are not "nice",
    // e.g. 26 days parses as "a month".
    return '24 hours';
  } else if (millis === 2 * 24 * 60 * 60 * 1000) {
    return '48 hours';
  } else {
    return Moment.duration(millis).humanize();
  }
}

function convertReportToAnalytics(fileType) {
  if (fileType === ExposureAppConstants.FILE_TYPE_REPORT) {
    fileType = ExposureAppConstants.FILE_TYPE_ANALYTICS;
  }
  return fileType;
}


module.exports = constants;
