module.exports = {
  DEFAULT_MOBILE_ROWS_PER_PAGE: 10,
  DEFAULT_ROWS_PER_PAGE: 20,
  LIST_VIEW_INVALID_QUERY: 'LIST_VIEW_INVALID_QUERY',
  LIST_VIEW_NOT_FOUND: 'LIST_VIEW_NOT_FOUND',
  LIST_VIEW_VALID: 'LIST_VIEW_VALID',
  ORDER_ASCENDING_STR: 'ASC',
  ORDER_DESCENDING_STR: 'DESC',
  ORDER_NONSORT_STR: 'NONE',
  PAGE_SIZE_DROPDOWN_ROWS: 6
};
