module.exports = {
  APERTURE_ACCOUNTS: 'accounts',
  APERTURE_SCHEMAS: 'schemas',
  APERTURE_SCHEMAS_EDIT: 'schemas_edit',
  APERTURE_SCHEMAS_GPP: 'schemas_gpp',
  APERTURE_SCHEMAS_NEW: 'schemas_new',
  APERTURE_SHARE_KPIS: 'share kpis',
  APERTURE_DATA_ACCESS_GROUPS: 'data_access_groups',
  APERTURE_DATA_ACCESS_GROUPS_EDIT: 'data_access_groups_edit',
  APERTURE_DATA_ACCESS_GROUPS_MANAGEMENT: 'data_access_groups_management',
  APERTURE_DATA_ACCESS_GROUPS_NEW: 'data_access_groups_new',
  APERTURE_DATA_REVIEW_ROLES: 'data_review_roles',
  APERTURE_DATA_REVIEW_ROLES_MANAGEMENT: 'data_review_roles_management',
  APERTURE_DATA_REVIEW_ROLES_NEW: 'data_review_roles_new',
  APERTURE_DATA_REVIEW_ROLES_EDIT: 'data_review_roles_edit',
  APERTURE_DISPOSITION_TERMS: 'dispositions',
  APERTURE_GROUPS: 'groups',
  APERTURE_GROUPS_EDIT: 'groups_edit',
  APERTURE_GROUPS_NEW: 'groups_new',
  APERTURE_USERS: 'users',
  APERTURE_USERS_LEGACY: 'users_legacy',
  APERTURE_USERS_SHOW: 'users_show',
  EXPOSURE_ADHOC_REPORTS_NEW: 'adhoc_reports_new',
  EXPOSURE_ADHOC_REPORTS_EDIT: 'adhoc_reports_edit',
  EXPOSURE_ALERTS: 'alerts',
  EXPOSURE_AUDIT_TRAIL_REPORTS: 'audit-trail-reports',
  EXPOSURE_BUILTIN_SHOW: 'builtins_show',
  EXPOSURE_DASHBOARDS_HOME: '/home/mydashboards',
  EXPOSURE_DASHBOARDS_EDIT: 'dashboards_edit',
  EXPOSURE_DASHBOARDS_NEW: 'dashboards_new',
  EXPOSURE_DASHBOARDS_SHOW: 'dashboards_show',
  EXPOSURE_DATA_REVIEW_NEW: 'data_review_new',
  EXPOSURE_DATA_REVIEW_EDIT: 'data_review_edit',
  EXPOSURE_DATA_REVIEW_SHOW: 'data_review_show',
  EXPOSURE_FAVORITES: 'favorites',
  EXPOSURE_FOLDERS: 'folders',
  EXPOSURE_FOLDERS_SHOW: 'folders_show',
  EXPOSURE_MONITORS_NEW: 'monitors_new',
  EXPOSURE_MONITORS_SHOW: 'monitors_show',
  EXPOSURE_MONITORS_EDIT: 'monitors_edit',
  EXPOSURE_QUALITY_AGREEMENTS_NEW: 'quality_agreements_new',
  EXPOSURE_QUALITY_AGREEMENTS_SHOW: 'quality_agreements_show',
  EXPOSURE_QUALITY_AGREEMENTS_EDIT: 'quality_agreements_edit',
  EXPOSURE_REPORTS: 'reports',
  EXPOSURE_REPORTS_EDIT: 'reports_edit',
  EXPOSURE_REPORTS_NEW: 'reports_new',
  EXPOSURE_REPORTS_SHOW: 'reports_show',
  EXPOSURE_TASKS: 'tasks',
  EXPOSURE_TASKS_NEW: 'tasks_new',
  EXPOSURE_TASKS_SHOW: 'tasks_show',
  EXPOSURE_EMBEDDED_TASKS_NEW: 'embedded_tasks_new',
  EXPOSURE_EMBEDDED_TASKS_SHOW: 'embedded_tasks_show',
  EXPOSURE_TEMPLATES: 'templates',
  EXPOSURE_TEMPLATES_EDIT: 'templates_edit',
  EXPOSURE_TEMPLATES_NEW: 'templates_new',
  EXPOSURE_TEMPLATES_EDIT_ADVANCED_REPORT: 'templates_edit_advanced_report',
  EXPOSURE_TEMPLATES_NEW_ADVANCED_REPORT: 'templates_new_advanced_report',
  EXPOSURE_EMBEDDED_DASHBOARDS_SHOW: 'embedded_dashboards_show',
  EXPOSURE_EMBEDDED_REPORTS_SHOW: 'embedded_reports_show',
  EXPOSURE_EMBEDDED_KPI_STUDIO_REPORTS_SHOW: 'embedded_kpi_studio_reports_show',
  EXPOSURE_EMBEDDED_GPP_REPORTS_DRILLDOWN: 'gpp_report_drilldown',
  EXPOSURE_YF_DASHBOARDS: 'my dashboards',
  EXPOSURE_YF_KPI_STUDIO: 'kpi studio',
  EXPOSURE_YF_CLINOPS_INSIGHTS: 'clinops insights',
  EXPOSURE_DATA_REVIEW_SET_TASKS_NEW: 'data_review_tasks_new',
  EXPOSURE_DATA_REVIEW_SET_TASKS_SHOW: 'data_review_tasks_show',
  EXPOSURE_EMBEDDED_CLINOPS_INSIGHTS_REPORTS_SHOW: 'embedded_clinops_insights_reports_show',
  EXPOSURE_HOME: 'home',
  EXPOSURE_HOME_EDITOR: '/home/edit',
  EXPOSURE_HOME_TEAM_EDITOR: '/home/teams/edit',
  EXPOSURE_HOME_WITH_TAB: 'home_with_tab',
  EXPOSURE_OVERSIGHT_SCORECARD: 'oversight scorecard',
  EXPOSURE_OVERSIGHT_SCORECARD_CONFIGURE: 'oversight-scorecard/configure',
  EXPOSURE_CREATE_RACT_TEMPLATE: 'ract/create-template',
  EXPOSURE_EDIT_RACT_TEMPLATE: 'ract/edit-template',
  EXPOSURE_VIEW_RACT_TEMPLATE: 'ract/view-template',
  EXPOSURE_DUPLICATE_RACT_TEMPLATE: 'ract/duplicate-template',
  EXPOSURE_RACT_TEMPLATE_CONFIGURATION: 'ract/ract-template-configuration',
  EXPOSURE_RACT_ASSESSMENT: 'ract/assessment',
  EXPOSURE_RACT_SIGN_OFF: 'ract/sign-off',
  EXPOSURE_RACT_ASSESSMENT_REVIEW: 'ract/assessment-review',
  EXPOSURE_RACT: 'ract',
  EXPOSURE_RBQM: 'rbqm',
  EXPOSURE_USER_PROFILE: '/user-profile',
  EXPOSURE_OPERATIONS_INSIGHTS: 'operations insights',
  EXPOSURE_OPERATIONS_INSIGHTS_REPORTS: 'operations insights/reports',
  EXPOSURE_RBM: 'rbm',
  EXPOSURE_CLINICAL_INSIGHTS: 'clinical insights',
  EXPOSURE_CLINICAL_INSIGHTS_REPORTS: 'clinical insights/reports',
  EXPOSURE_BOT_DASHBOARD: 'bot',
  TASK_CONFIGURATION: 'task-configuration'
};
