class HelpUtil {

  // In-App context aware help for file names.
  // If the current file's title appears in this list a question mark with a link into a new tab with
  // the report title spaces replaced by _ and appended .html
  // Within cqs-report repo execute the following to easily generate this list
  // cat deployment_templates/cqs_template.json | grep title | cut -d ':' -f2
  static helpDocs = [
    "Site Productivity",
    "Subject Enrollment",
    "Subject Compliance",
    "Portfolio Oversight Dashboard",
    "Study Dashboard",
    "Study Risk Dashboard",
    "Test Dashboard",
    "Adverse Events - Listing",
    "Concomitant Medication - Listing",
    "Lab - Listing",
    "Drug Accountability - Listing",
    "Field Data - Listing",
    "Primary Endpoint Field Data - Listing",
    "Missing Primary Endpoint Field Data - Listing",
    "Missing Required Field Data - Listing",
    "Missing SDV Field Data - Listing",
    "Monitoring Visits - Listing",
    "Protocol Deviations - Listing",
    "Queries - Listing",
    "Screen Failures - Listing",
    "Site Activation - Listing",
    "Site - Listing",
    "Site Issues - Listing",
    "Study Milestones - Listing",
    "Subject Disposition - Listing",
    "Subject Visit - Listing",
    "Latest Subject Visit - Listing",
    "AE Rate per Subject Days - Site",
    "AE Rate per Subject Days - Country",
    "AE Rate per Subject Days - Study",
    "AE Terms by Relative Study Week - Site",
    "AE Terms by Relative Study Week - Country",
    "AE Terms by Relative Study Week - Study",
    "Graphical Patient Profile",
    "AEs Against Study Baseline - Site",
    "AEs Against Study Baseline - Country",
    "AEs Against Study Baseline - Study",
    "Consent Rate - Site",
    "Consent Rate - Country",
    "Consent Rate - Study",
    "Data Entry Rate - Site",
    "Data Entry Rate - Country",
    "Data Entry Rate - Study",
    "Drug Accountability by Status - Site",
    "Drug Accountability by Status - Country",
    "Drug Accountability by Status - Study",
    "Subject Evaluable - Site",
    "Subject Evaluable - Country",
    "Subject Evaluable - Study",
    "Issue Resolution - Site",
    "Issue Resolution - Country",
    "Issue Resolution - Study",
    "Missing Data per Visit - Study",
    "Monitoring Visits Past Due - Country",
    "Monitoring Visits Past Due - Study",
    "Open & Answered Queries by Age - Site",
    "Open & Answered Queries by Age - Country",
    "Open & Answered Queries by Age - Study",
    "Primary Endpoint Data Entry Rate - Site",
    "Primary Endpoint Data Entry Rate - Country",
    "Primary Endpoint Data Entry Rate - Study",
    "Protocol Deviations Rate - Site",
    "Protocol Deviations Rate - Country",
    "Protocol Deviations Rate - Study",
    "Protocol Deviations per Subject per Visit - Site",
    "Protocol Deviations per Subject per Visit - Country",
    "Protocol Deviations per Subject per Visit - Study",
    "Query Rate - Site",
    "Query Rate - Country",
    "Query Rate - Study",
    "Query Rate by eCRF - Site",
    "Query Rate by eCRF - Country",
    "Query Rate by eCRF - Study",
    "Query Resolution - Site",
    "Query Resolution - Country",
    "Query Resolution - Study",
    "Randomization Failures by Reason - Site",
    "Randomization Failures by Reason - Country",
    "Randomization Failures by Reason - Study",
    "Screen Failures by Reason - Site",
    "Screen Failures by Reason - Country",
    "Screen Failures by Reason - Study",
    "Site Activation - Country",
    "Site Activation - Study",
    "Subject Count by Latest Scheduled Visit - Site",
    "Subject Count by Latest Scheduled Visit - Country",
    "Subject Count by Latest Scheduled Visit - Study",
    "Current Subject Disposition - Site",
    "Current Subject Disposition - Country",
    "Current Subject Disposition - Study",
    "Subject Withdrawal - Site",
    "Subject Withdrawal - Country",
    "Subject Withdrawal - Study",
    "Subject Enrollment Funnel - Study",
    "Subject Enrollment Rate - Site",
    "Subject Enrollment Rate - Country",
    "Subject Enrollment Rate - Study",
    "Subject Visit Compliance with Schedule - Site",
    "Subject Visit Compliance with Schedule - Country",
    "Subject Visit Compliance with Schedule - Study",
    "Portfolio Oversight",
    "Portfolio Dashboard",
    "Study Milestones",
    "Composite Risk Score Monitor",
    "Analytics",
    "Data Quality Dashboard",
    "Study Summary",
    "Portfolio Summary",
    "Financial Summary",
    "Site Summary",
    "Spend Analysis",
    "Spend Details",
    "Enrollment Dashboard - Study",
    "Site Activation Dashboard - Study",
    "Quality Measures Dashboard - Study",
    "Data Metrics Dashboard - Study",
    "Safety Summary Dashboard - Study",
    "Adverse Event Reporting Delay",
    "Data Refresh - Listing",  
    "Adverse Event - Toxicity Profile",
    "ae",
    "CQS - Monitor",
    "Hy's Law",
    "Lab Spaghetti Plot - Absolute Value",
    "Lab Spaghetti Plot - Baseline Deviation",
    "Site Performance - Study",
    "Site CRO Scorecard",
    "Site Performance Dashboard",
    "Site Specific Performance - Site",
    "Subject Event Log",
    "Subject Progression",
    "ALT vs BILI",
    "AST vs BILI",
    "DILI Lab Results Over Study Day",
    "Hy's Law Dashboard",
    "Missing SDV - Listing",
    "Open Query Rates - Listing",
    "Screen Failure Rates - Listing",
    "Subject Days by Subject - Listing",
    "Withdrawal Rates - Listing",
    "Subject Early EOT - Study",
    "Subject Early EOT - Site",
    "Subject Early EOT - Country",
    "Enrollment Rates - Listing",
    "AE Rates - Listing",
    "PD Rates - Listing",
    "ae Review Set",
    "CQS - Daily data monitors status",
    "Data Review Summary",
    "CRO Scorecard",
    "Tasks Analytics"
  ];

  static isInAppHelpExists(title) {
    return _.contains(this.helpDocs, title)
  }

}

module.exports = HelpUtil;
